package IMPORTANTE;

import DTOS.ComprasDto;
import DAOS.ComprasDao;
import java.awt.Color;
import java.awt.Font;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import java.sql.Date;
import java.text.DecimalFormat;
import java.util.Calendar;
public class Compras extends javax.swing.JInternalFrame {
    public Compras() {
        initComponents();
        txtIdCompras.setVisible(false);
        txtIdCompras.setEnabled(false);
        limpiar();
        habilitar(true);
        mostrarBuscar("");
        
       
    }
    
    public void addplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
       
    }
    public void deleteplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public void mostrarBuscar(String usuario) {
        DefaultTableModel miModelo;
       ComprasDao compDao = new ComprasDao();
        ComprasDto compDto = new ComprasDto();
        compDto.setArticulo(usuario);
        miModelo = compDao.mostrarCompras(compDto);
        tblCompras.setModel(miModelo);

    }
    

    public void limpiar() {
        txtIdCompras.setText("");
        txtArticulo.setText("");
        txtCantidad.setText("");
        txtFecha.setText("");
        
       
        txtBuscar.setText("");
    }

    public void habilitar(boolean b) {
        txtArticulo.setEnabled(!b);
        txtCantidad.setEnabled(!b);
        txtFecha.setEnabled(!b);
        txtDesc.setEnabled(!b);
       
        btnNuevo.setEnabled(b);
        btnEditar.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        txtArticulo = new javax.swing.JTextField();
        txtIdCompras = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(909, 480));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        txtArticulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArticuloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArticuloFocusLost(evt);
            }
        });
        txtArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArticuloKeyTyped(evt);
            }
        });
        jPanel1.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 140, -1));

        txtIdCompras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdComprasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdComprasFocusLost(evt);
            }
        });
        txtIdCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdComprasKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 10, 10));

        txtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaFocusLost(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo (1).png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 30));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("Articulo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel9.setText("Descripción:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("Cantidad:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescFocusLost(evt);
            }
        });
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescKeyTyped(evt);
            }
        });
        jPanel1.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMPRAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblCompras.setBackground(new java.awt.Color(153, 153, 255));
        tblCompras.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Articulo", "Cantidad", "Descripción", "Fecha Solicitud"
            }
        ));
        tblCompras.setSelectionBackground(new java.awt.Color(255, 102, 255));
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblComprasMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompras);

        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (3).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        habilitar(false);
        
                
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseClicked
        // TODO add your handling code here:
        int fila = tblCompras.getSelectedRow();
        txtIdCompras.setText(tblCompras.getValueAt(fila, 0).toString());
        txtArticulo.setText(tblCompras.getValueAt(fila, 1).toString());
        txtCantidad.setText(tblCompras.getValueAt(fila, 2).toString());
        txtDesc.setText(tblCompras.getValueAt(fila, 3).toString());
        txtFecha.setText(tblCompras.getValueAt(fila, 4).toString());
     //   txtFecha.setString(tblCompras.getValueAt(fila, 4).toString());
       
    }//GEN-LAST:event_tblComprasMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        mostrarBuscar(txtBuscar.getText());
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIdComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdComprasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdComprasKeyTyped

    private void txtArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticuloKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtArticuloKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        
    }//GEN-LAST:event_txtFechaKeyTyped

    /*
    txtId.setText("Ingrese su ID");
        txtNombre.setText("Ingrese su Nombre");
        txtUsuario.setText("Ingrese su Usuario");
        txtnFicha.setText("Ingrese su N.Ficha");
        txtnControl.setText("Ingrese su N.Control");
        txtCarrera.setText("Ingrese su Carrera");
        txtTurno.setText("Ingrese su Turno");
        txtPuesto.setText("Ingrese su Puesto");
        txtInstitucion.setText("Ingrese su Institución");
        txtEscuela.setText("Ingrese su Escuela");
        txtClave.setText("Ingrese su Clave");
        txtConfirmarClave.setText("Confirme su Clave");
        txtBuscar.setText("Ingrese el ID");
    */
    
    private void txtIdComprasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdComprasFocusGained
      if(txtIdCompras.getText().equals("")){
         txtIdCompras.setText(null);
         txtIdCompras.requestFocus();
         deleteplaceholder(txtIdCompras);
      //Ingrese el ID   
     }
    }//GEN-LAST:event_txtIdComprasFocusGained

    private void txtIdComprasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdComprasFocusLost
          if(txtIdCompras.getText().length()==0){
          addplaceholder(txtIdCompras);
          //txtIdUsuarios.setText("Ingrese su ID");
      }
    }//GEN-LAST:event_txtIdComprasFocusLost

    private void txtArticuloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticuloFocusGained
       /* if(txtNombre.getText().equals("")){
         txtNombre.setText(null);
         txtNombre.requestFocus();
         deleteplaceholder(txtNombre);
       
     } */
    }//GEN-LAST:event_txtArticuloFocusGained

    private void txtArticuloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticuloFocusLost
        if(txtArticulo.getText().length()==0){
          addplaceholder(txtArticulo);
       //   txtNombre.setText("Ingrese su Nombre");
      }
    }//GEN-LAST:event_txtArticuloFocusLost

    private void txtCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusGained
       if(txtCantidad.getText().equals("")){
         txtCantidad.setText(null);
         txtCantidad.requestFocus();
         deleteplaceholder(txtCantidad);
      
     }
    }//GEN-LAST:event_txtCantidadFocusGained

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        if(txtCantidad.getText().length()==0){
          addplaceholder(txtCantidad);
          //txtUsuario.setText("Ingrese su Usuario");
      }
    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusGained
      if(txtFecha.getText().equals("")){
         txtFecha.setText(null);
         txtFecha.requestFocus();
         deleteplaceholder(txtFecha);
       }
    }//GEN-LAST:event_txtFechaFocusGained

    private void txtFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusLost
        
    }//GEN-LAST:event_txtFechaFocusLost

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
          
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
       
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
       
    }//GEN-LAST:event_txtBuscarFocusLost

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void tblComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseExited
       
    }//GEN-LAST:event_tblComprasMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        String msg = null;
        if (txtArticulo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Articulo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtArticulo.requestFocusInWindow();
            return;
        }
        if (txtCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtCantidad.requestFocusInWindow();
            return;
        }
         if (txtDesc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Descripción obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocusInWindow();
            return;
        }
        if (txtFecha.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Fecha obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocusInWindow();
            return;
        }
      /*
        if (txtFecha2.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Campo fecha obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocusInWindow();
            return;
        }  */
      
        if (txtIdCompras.getText().equals("")) {
             ComprasDao compDao = new ComprasDao();
             ComprasDto compDto = new ComprasDto(); 
      
         
            compDto.setArticulo(txtArticulo.getText() );
            compDto.setCantidad(txtCantidad.getText());
            compDto.setDescripcion(txtFecha.getText());
            compDto.setFecha(txtFecha.getText());
            //compDto.setFecha(new Date(aa, mm, dd));
            msg = compDao.insertarCompras(compDto);
                 
            JOptionPane.showMessageDialog(rootPane, msg, "Usuario Agregado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ComprasDao compDao = new ComprasDao();
             ComprasDto compDto = new ComprasDto(); 
      
       /*        Calendar cal;

        cal = txtFecha2.getCalendar();

        int aa, mm, dd;

        aa = cal.get(Calendar.YEAR) - 1900;
        mm = cal.get(Calendar.MONTH);
        dd = cal.get(Calendar.DAY_OF_MONTH);  */

             
            compDto.setIdcompras(Integer.parseInt(txtIdCompras.getText()));
            compDto.setArticulo(txtArticulo.getText() );
            compDto.setCantidad(txtCantidad.getText());
            compDto.setDescripcion(txtDesc.getText());
            compDto.setFecha(txtFecha.getText());
           //compDto.setFecha(new Date(aa, mm, dd));
            
            msg= compDao.editarCompras(compDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Usuario Modificado", JOptionPane.INFORMATION_MESSAGE);
        }
       
       
        
        habilitar(true);
        mostrarBuscar("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
        mostrarBuscar("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         String msg = null;
        if (txtIdCompras.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un registro de la tabla para eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            ComprasDao compDao = new ComprasDao();
             ComprasDto compDto = new ComprasDto(); 
             
             compDto.setIdcompras(Integer.parseInt(txtIdCompras.getText()));
             msg= compDao.eliminarCompras(compDto);
        
            JOptionPane.showMessageDialog(rootPane, msg, "Compra Eliminada", JOptionPane.INFORMATION_MESSAGE);
        }
        mostrarBuscar("");
       
       limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDescFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescFocusGained

    private void txtDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescFocusLost

    private void txtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdCompras;
    // End of variables declaration//GEN-END:variables

}
