
package IMPORTANTE;

import DTOS.CubiculosDto;
import DAOS.CubiculosDao;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class Cubiculos extends javax.swing.JInternalFrame {

    public Cubiculos() {
        initComponents();
        txtIdCubi.setVisible(false);
        txtIdCubi.setEnabled(false);
        limpiar();
        habilitar(true);
        mostrarBuscar("");
        
       
    }
    
    public void addplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
       
    }
    public void deleteplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public void mostrarBuscar(String cubiculo) {
        DefaultTableModel miModelo;
        CubiculosDao cubiDao = new CubiculosDao();
        CubiculosDto cubiDto = new CubiculosDto();
        cubiDto.setCodigoCubi(cubiculo);
        miModelo = cubiDao.mostrarSalones(cubiDto);
        tblCubiculos.setModel(miModelo);

    }

    public void limpiar() {
        txtIdCubi.setText("");
        txtCodigo.setText("");
        txtImpresora.setText("");
        txtFI.setText("");
        txtSilla.setText("");
        txtFS.setText("");
        txtMesa.setText("");
        txtFM.setText("");
        txtPC.setText("");
        txtFPC.setText("");
        txtLibrero.setText("");
        txtFli.setText("");
        txtBote.setText("");
        txtFBB.setText("");
        txtCentroman.setText("");
        txtFCM.setText("");
        
        txtUbi.setText("");
        txtObser.setText("");
        txtBuscarSalon.setText("");
    }

    public void habilitar(boolean b) {
        txtCodigo.setEnabled(!b);
        txtImpresora.setEnabled(!b);
        txtFI.setEnabled(!b);
        txtSilla.setEnabled(!b);
        txtFS.setEnabled(!b);
        txtMesa.setEnabled(!b);
        txtFM.setEnabled(!b);
        txtPC.setEnabled(!b);
        txtFPC.setEnabled(!b);
        txtLibrero.setEnabled(!b);
        txtFli.setEnabled(!b);
        txtBote.setEnabled(!b);
        txtFBB.setEnabled(!b);
        txtCentroman.setEnabled(!b);
        txtFCM.setEnabled(!b);
       
        txtUbi.setEnabled(!b);
        txtObser.setEnabled(!b);
      

        btnNuevo.setEnabled(b);
        btnEditar.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtImpresora = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtIdCubi = new javax.swing.JTextField();
        txtFI = new javax.swing.JTextField();
        txtSilla = new javax.swing.JTextField();
        txtFS = new javax.swing.JTextField();
        txtMesa = new javax.swing.JTextField();
        txtFM = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtFPC = new javax.swing.JTextField();
        txtLibrero = new javax.swing.JTextField();
        txtFli = new javax.swing.JTextField();
        txtBote = new javax.swing.JTextField();
        txtFBB = new javax.swing.JTextField();
        txtCentroman = new javax.swing.JTextField();
        txtFCM = new javax.swing.JTextField();
        txtUbi = new javax.swing.JTextField();
        txtObser = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCubiculos = new javax.swing.JTable();
        txtBuscarSalon = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(909, 480));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtImpresora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtImpresoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtImpresoraFocusLost(evt);
            }
        });
        txtImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpresoraActionPerformed(evt);
            }
        });
        txtImpresora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImpresoraKeyTyped(evt);
            }
        });
        jPanel1.add(txtImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 58, -1));

        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        txtIdCubi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdCubiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdCubiFocusLost(evt);
            }
        });
        txtIdCubi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdCubiKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdCubi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 14, 7));

        txtFI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFIFocusLost(evt);
            }
        });
        txtFI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFIKeyTyped(evt);
            }
        });
        jPanel1.add(txtFI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, -1));

        txtSilla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSillaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSillaFocusLost(evt);
            }
        });
        txtSilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSillaKeyTyped(evt);
            }
        });
        jPanel1.add(txtSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 58, -1));

        txtFS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFSFocusLost(evt);
            }
        });
        txtFS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFSKeyTyped(evt);
            }
        });
        jPanel1.add(txtFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, -1));

        txtMesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMesaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesaFocusLost(evt);
            }
        });
        txtMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesaKeyTyped(evt);
            }
        });
        jPanel1.add(txtMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 58, -1));

        txtFM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMFocusLost(evt);
            }
        });
        txtFM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFMKeyTyped(evt);
            }
        });
        jPanel1.add(txtFM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 40, -1));

        txtPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPCFocusLost(evt);
            }
        });
        txtPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 58, -1));

        txtFPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPCFocusLost(evt);
            }
        });
        txtFPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtFPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 40, -1));

        txtLibrero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLibreroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLibreroFocusLost(evt);
            }
        });
        txtLibrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibreroActionPerformed(evt);
            }
        });
        txtLibrero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibreroKeyTyped(evt);
            }
        });
        jPanel1.add(txtLibrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 58, -1));

        txtFli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFliFocusLost(evt);
            }
        });
        txtFli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFliKeyTyped(evt);
            }
        });
        jPanel1.add(txtFli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 40, -1));

        txtBote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBoteFocusLost(evt);
            }
        });
        txtBote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBoteKeyTyped(evt);
            }
        });
        jPanel1.add(txtBote, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 58, -1));

        txtFBB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFBBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFBBFocusLost(evt);
            }
        });
        txtFBB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFBBKeyTyped(evt);
            }
        });
        jPanel1.add(txtFBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 40, -1));

        txtCentroman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCentromanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCentromanFocusLost(evt);
            }
        });
        txtCentroman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCentromanKeyTyped(evt);
            }
        });
        jPanel1.add(txtCentroman, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 58, -1));

        txtFCM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFCMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFCMFocusLost(evt);
            }
        });
        txtFCM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFCMKeyTyped(evt);
            }
        });
        jPanel1.add(txtFCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 40, -1));

        txtUbi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUbiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUbiFocusLost(evt);
            }
        });
        txtUbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUbiKeyTyped(evt);
            }
        });
        jPanel1.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 115, -1));

        txtObser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtObserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObserFocusLost(evt);
            }
        });
        txtObser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObserKeyTyped(evt);
            }
        });
        jPanel1.add(txtObser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 115, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo (1).png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 30));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setText("Fun:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("Fun:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel8.setText("Fun:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel9.setText("Fun:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("Fun:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel11.setText("Fun:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel12.setText("Fun:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel20.setText("Ubi:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setText("Notas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setText("Imp:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setText("Silla:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel13.setText("Mes:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel14.setText("PC:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel15.setText("Lib:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel16.setText("Bote:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel17.setText("CM:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUBÍCULOS\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        tblCubiculos.setBackground(new java.awt.Color(153, 153, 255));
        tblCubiculos.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tblCubiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "USUARIO", "NFicha", "NControl", "Carrera", "Turno", "Puesto", "Institucion", "Escuela", "PERFIL"
            }
        ));
        tblCubiculos.setSelectionBackground(new java.awt.Color(255, 102, 255));
        tblCubiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCubiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCubiculos);

        txtBuscarSalon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusLost(evt);
            }
        });
        txtBuscarSalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarSalonKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (3).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        habilitar(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblCubiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCubiculosMouseClicked
        // TODO add your handling code here:
        int fila = tblCubiculos.getSelectedRow();
        txtIdCubi.setText(tblCubiculos.getValueAt(fila, 0).toString());
        txtCodigo.setText(tblCubiculos.getValueAt(fila, 1).toString());
        txtImpresora.setText(tblCubiculos.getValueAt(fila, 2).toString());
        txtFI.setText(tblCubiculos.getValueAt(fila, 3).toString());
        txtSilla.setText(tblCubiculos.getValueAt(fila, 4).toString());
        txtFS.setText(tblCubiculos.getValueAt(fila, 5).toString());
        txtMesa.setText(tblCubiculos.getValueAt(fila, 6).toString());
        txtFM.setText(tblCubiculos.getValueAt(fila, 7).toString());
        txtPC.setText(tblCubiculos.getValueAt(fila, 8).toString());
        txtFPC.setText(tblCubiculos.getValueAt(fila, 9).toString());
        txtLibrero.setText(tblCubiculos.getValueAt(fila, 10).toString());
        txtFli.setText(tblCubiculos.getValueAt(fila, 11).toString());
        txtBote.setText(tblCubiculos.getValueAt(fila, 12).toString());
        txtFBB.setText(tblCubiculos.getValueAt(fila, 13).toString());
        txtCentroman.setText(tblCubiculos.getValueAt(fila, 14).toString());
        txtFCM.setText(tblCubiculos.getValueAt(fila, 15).toString());
        txtUbi.setText(tblCubiculos.getValueAt(fila, 16).toString());
        txtObser.setText(tblCubiculos.getValueAt(fila, 17).toString());
        
                
    }//GEN-LAST:event_tblCubiculosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        mostrarBuscar(txtBuscarSalon.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIdCubiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCubiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCubiKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtImpresoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImpresoraKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtImpresoraKeyTyped

    private void txtFIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFIKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFIKeyTyped

    private void txtSillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSillaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtSillaKeyTyped

    private void txtFSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFSKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFSKeyTyped

    private void txtMesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesaKeyTyped
  char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtMesaKeyTyped

    private void txtFMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFMKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFMKeyTyped

    private void txtPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPCKeyTyped

    private void txtFPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPCKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPCKeyTyped

    /*
    txtId.setText("Ingrese su ID");
        txtNombre.setText("Ingrese su Nombre");
        txtUsuario.setText("Ingrese su Usuario");
        txtnFicha.setText("Ingrese su N.Ficha");
        txtnControl.setText("Ingrese su N.Control");
        txtCarrera.setText("Ingrese su Carrera");
        txtTurno.setText("Ingrese su Turno");
        txtPuesto.setText("Ingrese su Puesto");
        txtInstitucion.setText("Ingrese su Institución");
        txtEscuela.setText("Ingrese su Escuela");
        txtClave.setText("Ingrese su Clave");
        txtConfirmarClave.setText("Confirme su Clave");
        txtBuscar.setText("Ingrese el ID");
    */
    
    private void txtIdCubiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdCubiFocusGained
     
    }//GEN-LAST:event_txtIdCubiFocusGained

    private void txtIdCubiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdCubiFocusLost
         
    }//GEN-LAST:event_txtIdCubiFocusLost

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
       
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
       
    }//GEN-LAST:event_txtCodigoFocusLost

    private void txtImpresoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImpresoraFocusGained
       
    }//GEN-LAST:event_txtImpresoraFocusGained

    private void txtImpresoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImpresoraFocusLost
       
    }//GEN-LAST:event_txtImpresoraFocusLost

    private void txtFIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFIFocusGained
      
    }//GEN-LAST:event_txtFIFocusGained

    private void txtFIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFIFocusLost
      
    }//GEN-LAST:event_txtFIFocusLost

    private void txtSillaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusGained
      
    }//GEN-LAST:event_txtSillaFocusGained

    private void txtSillaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusLost
      
    }//GEN-LAST:event_txtSillaFocusLost

    private void txtFSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusGained
      
    }//GEN-LAST:event_txtFSFocusGained

    private void txtFSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusLost
      
    }//GEN-LAST:event_txtFSFocusLost

    private void txtMesaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusGained
     
    }//GEN-LAST:event_txtMesaFocusGained

    private void txtMesaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusLost
     
    }//GEN-LAST:event_txtMesaFocusLost

    private void txtFMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusGained
     
    }//GEN-LAST:event_txtFMFocusGained

    private void txtFMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusLost
     
    }//GEN-LAST:event_txtFMFocusLost

    private void txtPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusGained
     
    }//GEN-LAST:event_txtPCFocusGained

    private void txtPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusLost
     
    }//GEN-LAST:event_txtPCFocusLost

    private void txtFPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusGained
     
    }//GEN-LAST:event_txtFPCFocusGained

    private void txtFPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusLost
     
    }//GEN-LAST:event_txtFPCFocusLost

    private void txtBuscarSalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSalonKeyTyped
         
    }//GEN-LAST:event_txtBuscarSalonKeyTyped

    private void txtBuscarSalonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusGained
        
     
    }//GEN-LAST:event_txtBuscarSalonFocusGained

    private void txtBuscarSalonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusLost
     
    }//GEN-LAST:event_txtBuscarSalonFocusLost

    private void txtImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpresoraActionPerformed

    private void txtLibreroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibreroFocusGained
       if(txtLibrero.getText().equals("Cantidad de Proyectores")){
         txtLibrero.setText(null);
         txtLibrero.requestFocus();
         deleteplaceholder(txtLibrero);
     }
    }//GEN-LAST:event_txtLibreroFocusGained

    private void txtLibreroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibreroFocusLost
        if(txtLibrero.getText().length()==0){
          addplaceholder(txtLibrero);
          txtLibrero.setText("Cantidad de Proyectores");
      }
    }//GEN-LAST:event_txtLibreroFocusLost

    private void txtLibreroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibreroKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtLibreroKeyTyped

    private void txtFliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFliFocusGained
        if(txtFli.getText().equals("Funciona")){
         txtFli.setText(null);
         txtFli.requestFocus();
         deleteplaceholder(txtFli);
     }
    }//GEN-LAST:event_txtFliFocusGained

    private void txtFliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFliFocusLost
       if(txtFli.getText().length()==0){
          addplaceholder(txtFli);
          txtFli.setText("Funciona");
      }
    }//GEN-LAST:event_txtFliFocusLost

    private void txtFliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFliKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFliKeyTyped

    private void txtBoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusGained
        if(txtBote.getText().equals("Cantidad de Botes")){
         txtBote.setText(null);
         txtBote.requestFocus();
         deleteplaceholder(txtBote);
     }
    }//GEN-LAST:event_txtBoteFocusGained

    private void txtBoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusLost
        if(txtBote.getText().length()==0){
          addplaceholder(txtBote);
          txtBote.setText("Cantidad de Botes");
      }
    }//GEN-LAST:event_txtBoteFocusLost

    private void txtBoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoteKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBoteKeyTyped

    private void txtFBBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusGained
          if(txtFBB.getText().equals("Funciona")){
         txtFBB.setText(null);
         txtFBB.requestFocus();
         deleteplaceholder(txtFBB);
     }
    }//GEN-LAST:event_txtFBBFocusGained

    private void txtFBBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusLost
       if(txtFBB.getText().length()==0){
          addplaceholder(txtFBB);
          txtFBB.setText("Funciona");
      }
    }//GEN-LAST:event_txtFBBFocusLost

    private void txtFBBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFBBKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFBBKeyTyped

    private void txtCentromanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCentromanFocusGained
        if(txtCentroman.getText().equals("Cantidad de Mesabancos")){
         txtCentroman.setText(null);
         txtCentroman.requestFocus();
         deleteplaceholder(txtCentroman);
     }
    }//GEN-LAST:event_txtCentromanFocusGained

    private void txtCentromanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCentromanFocusLost
        if(txtCentroman.getText().length()==0){
          addplaceholder(txtCentroman);
          txtCentroman.setText("Cantidad de Mesabancos");
      }
    }//GEN-LAST:event_txtCentromanFocusLost

    private void txtCentromanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCentromanKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCentromanKeyTyped

    private void txtFCMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCMFocusGained
         if(txtFCM.getText().equals("Funciona")){
         txtFCM.setText(null);
         txtFCM.requestFocus();
         deleteplaceholder(txtFCM);
     }
    }//GEN-LAST:event_txtFCMFocusGained

    private void txtFCMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCMFocusLost
       if(txtFCM.getText().length()==0){
          addplaceholder(txtFCM);
          txtFCM.setText("Funciona");
      }
    }//GEN-LAST:event_txtFCMFocusLost

    private void txtFCMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFCMKeyTyped
       char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFCMKeyTyped

    private void txtUbiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusGained
            if(txtUbi.getText().equals("Ingrese la Ubicación")){
         txtUbi.setText(null);
         txtUbi.requestFocus();
         deleteplaceholder(txtUbi);
     }
    }//GEN-LAST:event_txtUbiFocusGained

    private void txtUbiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusLost
     if(txtUbi.getText().length()==0){
          addplaceholder(txtUbi);
          txtUbi.setText("Ingrese la Ubicación");
      }
    }//GEN-LAST:event_txtUbiFocusLost

    private void txtUbiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbiKeyTyped
      
    }//GEN-LAST:event_txtUbiKeyTyped

    private void txtObserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusGained
          if(txtObser.getText().equals("Ingrese la Observación")){
         txtObser.setText(null);
         txtObser.requestFocus();
         deleteplaceholder(txtObser);
         
     }
    }//GEN-LAST:event_txtObserFocusGained

    private void txtObserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusLost
        if(txtObser.getText().length()==0){
          addplaceholder(txtObser);
          txtObser.setText("Ingrese la Observación");
      }
    }//GEN-LAST:event_txtObserFocusLost

    private void txtObserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObserKeyTyped
     
    }//GEN-LAST:event_txtObserKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
 String msg = null;
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtCodigo.requestFocusInWindow();
            return;
        }
        if (txtImpresora.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Impresoras es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtImpresora.requestFocusInWindow();
            return;
        }
        if(txtFI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funciona Pizarrón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFI.requestFocusInWindow();
            return;
        }
        if(txtSilla.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtSilla.requestFocusInWindow();
            return;
        }
        if(txtFS.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFS.requestFocusInWindow();
            return;
        }
        if(txtMesa.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtMesa.requestFocusInWindow();
            return;
        }
        if(txtFM.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFM.requestFocusInWindow();
            return;
        }
        if(txtPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPC.requestFocusInWindow();
            return;
        }
        if(txtFPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFPC.requestFocusInWindow();
            return;
        }
        if(txtLibrero.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Libreros es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtLibrero.requestFocusInWindow();
            return;
        }
        if(txtFli.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Libreros es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFli.requestFocusInWindow();
            return;
        }
        if(txtBote.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBote.requestFocusInWindow();
            return;
        }
        if(txtFBB.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBB.requestFocusInWindow();
            return;
        }
        if(txtCentroman.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Centro de Mando es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtCentroman.requestFocusInWindow();
            return;
        }
        if(txtFCM.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Centro de Mando es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFCM.requestFocusInWindow();
            return;
        }
       
        if(txtUbi.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Ubicación de Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtUbi.requestFocusInWindow();
            return;
        }
         if (txtIdCubi.getText().equals("")) {
            CubiculosDto cubiDto = new CubiculosDto();
            CubiculosDao cubiDao = new CubiculosDao();

            
            //    cubiculos (id_Cubi,codigoCubi, impresora,fi,silla,fs,mesa, fm,pc,fpc,librero,fli,boteBa,fbb,CentroMan,fcm  ,ubi,obser)

            cubiDto.setCodigoCubi(txtCodigo.getText());
            cubiDto.setImpresora(txtImpresora.getText());
            cubiDto.setFi(txtFI.getText());
            cubiDto.setSilla(txtSilla.getText());
            cubiDto.setFs(txtFS.getText());
            cubiDto.setMesa(txtMesa.getText());
            cubiDto.setFm(txtFM.getText());
            cubiDto.setPc(txtPC.getText());
            cubiDto.setFpc(txtFPC.getText());
            cubiDto.setLibrero(txtLibrero.getText());
            cubiDto.setFli(txtFli.getText());
            cubiDto.setBoteBa(txtBote.getText());
            cubiDto.setFbb(txtFBB.getText());
            cubiDto.setCentroMan(txtCentroman.getText());
            cubiDto.setFcm(txtFCM.getText());
            cubiDto.setUbi(txtUbi.getText());
            cubiDto.setObser(txtObser.getText());
                    
                    
            msg = cubiDao.insertarCubiculos(cubiDto);
                   
            JOptionPane.showMessageDialog(rootPane, msg, "Cubículo Añadido", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
             CubiculosDto cubiDto = new CubiculosDto();
            CubiculosDao cubiDao = new CubiculosDao();

            
            //    cubiculos (id_Cubi,codigoCubi, impresora,fi,silla,fs,mesa, fm,pc,fpc,librero,fli,boteBa,fbb,CentroMan,fcm  ,ubi,obser)

            cubiDto.setId_Cubi(Integer.parseInt(txtIdCubi.getText()));
            cubiDto.setCodigoCubi(txtCodigo.getText());
            cubiDto.setImpresora(txtImpresora.getText());
            cubiDto.setFi(txtFI.getText());
            cubiDto.setSilla(txtSilla.getText());
            cubiDto.setFs(txtFS.getText());
            cubiDto.setMesa(txtMesa.getText());
            cubiDto.setFm(txtFM.getText());
            cubiDto.setPc(txtPC.getText());
            cubiDto.setFpc(txtFPC.getText());
            cubiDto.setLibrero(txtLibrero.getText());
            cubiDto.setFli(txtFli.getText());
            cubiDto.setBoteBa(txtBote.getText());
            cubiDto.setFbb(txtFBB.getText());
            cubiDto.setCentroMan(txtCentroman.getText());
            cubiDto.setFcm(txtFCM.getText());
            cubiDto.setUbi(txtUbi.getText());
            cubiDto.setObser(txtObser.getText());
            

            msg = cubiDao.editarCubiculos(cubiDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Cubículo Modificado", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
       limpiar();
        habilitar(true);
        mostrarBuscar("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
        mostrarBuscar("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         String msg = null;
        if (txtIdCubi.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un registro de la tabla para eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            
           CubiculosDto cubiDto = new CubiculosDto();
            CubiculosDao cubiDao = new CubiculosDao();
            
            cubiDto.setId_Cubi(Integer.parseInt(txtIdCubi.getText()));
            msg = cubiDao.eliminarCubiculos(cubiDto);
           
        
            JOptionPane.showMessageDialog(rootPane, msg, "Cubiculos Eliminado", JOptionPane.INFORMATION_MESSAGE);
        }
        mostrarBuscar("");
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtLibreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibreroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibreroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCubiculos;
    private javax.swing.JTextField txtBote;
    private javax.swing.JTextField txtBuscarSalon;
    private javax.swing.JTextField txtCentroman;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFBB;
    private javax.swing.JTextField txtFCM;
    private javax.swing.JTextField txtFI;
    private javax.swing.JTextField txtFM;
    private javax.swing.JTextField txtFPC;
    private javax.swing.JTextField txtFS;
    private javax.swing.JTextField txtFli;
    private javax.swing.JTextField txtIdCubi;
    private javax.swing.JTextField txtImpresora;
    private javax.swing.JTextField txtLibrero;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtObser;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtSilla;
    private javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables

}
