
package IMPORTANTE;

import DTOS.JefesDto;
import DAOS.JefesDao;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class Jefes extends javax.swing.JInternalFrame {

    public Jefes() {
        initComponents();
        txtIdJe.setVisible(false);
        txtIdJe.setEnabled(false);
        limpiar();
        habilitar(true);
        mostrarBuscar("");
        
  
       
    }
    
    
    public void addplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
       
    }
    public void deleteplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public void mostrarBuscar(String salon) {
        DefaultTableModel miModelo;
        JefesDao jefDao = new JefesDao();
        JefesDto jefDto = new JefesDto();
        jefDto.setCodigoJ(salon);
        miModelo = jefDao.mostrarJefes(jefDto);
        tblJefes.setModel(miModelo);

    }

    public void limpiar() {
        txtIdJe.setText("");
        txtCodigoJe.setText("");
        txtPizarron.setText("");
        txtFP.setText("");
        txtMesa.setText("");
        txtFM.setText("");
        txtSilla.setText("");
        txtFS.setText("");
        txtPC.setText("");
        txtFPC.setText("");
        txtLibrero.setText("");
        txtFli.setText("");
        txtBote.setText("");
        txtFBB.setText("");
        txtBaño.setText("");
        txtFBA.setText("");
        txtMueble.setText("");
        txtFMU.setText("");
        txtImpresora.setText("");
        txtFI.setText("");
        txtUbi.setText("");
        txtObser.setText("");
        txtBuscarSalon.setText("");
    }

    public void habilitar(boolean b) {
        txtCodigoJe.setEnabled(!b);
        txtPizarron.setEnabled(!b);
        txtFP.setEnabled(!b);
        txtMesa.setEnabled(!b);
        txtFM.setEnabled(!b);
        txtSilla.setEnabled(!b);
        txtFS.setEnabled(!b);
        txtPC.setEnabled(!b);
        txtFPC.setEnabled(!b);
        txtLibrero.setEnabled(!b);
        txtFli.setEnabled(!b);
        txtBote.setEnabled(!b);
        txtFBB.setEnabled(!b);
        txtBaño.setEnabled(!b);
        txtFBA.setEnabled(!b);
        txtMueble.setEnabled(!b);
        txtFMU.setEnabled(!b);
        txtImpresora.setEnabled(!b);
        txtFI.setEnabled(!b);
        txtUbi.setEnabled(!b);
        txtObser.setEnabled(!b);
      

        btnNuevo.setEnabled(b);
        btnEditar.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPizarron = new javax.swing.JTextField();
        txtCodigoJe = new javax.swing.JTextField();
        txtIdJe = new javax.swing.JTextField();
        txtFP = new javax.swing.JTextField();
        txtMesa = new javax.swing.JTextField();
        txtFM = new javax.swing.JTextField();
        txtSilla = new javax.swing.JTextField();
        txtFS = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtFPC = new javax.swing.JTextField();
        txtLibrero = new javax.swing.JTextField();
        txtFli = new javax.swing.JTextField();
        txtBote = new javax.swing.JTextField();
        txtFBB = new javax.swing.JTextField();
        txtBaño = new javax.swing.JTextField();
        txtFBA = new javax.swing.JTextField();
        txtUbi = new javax.swing.JTextField();
        txtObser = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        txtMueble = new javax.swing.JTextField();
        txtFMU = new javax.swing.JTextField();
        txtImpresora = new javax.swing.JTextField();
        txtFI = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJefes = new javax.swing.JTable();
        txtBuscarSalon = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(909, 480));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPizarron.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPizarronFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPizarronFocusLost(evt);
            }
        });
        txtPizarron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPizarronActionPerformed(evt);
            }
        });
        txtPizarron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPizarronKeyTyped(evt);
            }
        });
        jPanel1.add(txtPizarron, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 68, 56, -1));

        txtCodigoJe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoJeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoJeFocusLost(evt);
            }
        });
        txtCodigoJe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoJeKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigoJe, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 42, 88, -1));

        txtIdJe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdJeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdJeFocusLost(evt);
            }
        });
        txtIdJe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdJeKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdJe, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 29, 14, 7));

        txtFP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPFocusLost(evt);
            }
        });
        txtFP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPKeyTyped(evt);
            }
        });
        jPanel1.add(txtFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 42, -1));

        txtMesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMesaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesaFocusLost(evt);
            }
        });
        txtMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesaKeyTyped(evt);
            }
        });
        jPanel1.add(txtMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 56, -1));

        txtFM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMFocusLost(evt);
            }
        });
        txtFM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFMKeyTyped(evt);
            }
        });
        jPanel1.add(txtFM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 42, -1));

        txtSilla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSillaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSillaFocusLost(evt);
            }
        });
        txtSilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSillaKeyTyped(evt);
            }
        });
        jPanel1.add(txtSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 56, -1));

        txtFS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFSFocusLost(evt);
            }
        });
        txtFS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFSKeyTyped(evt);
            }
        });
        jPanel1.add(txtFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 42, -1));

        txtPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPCFocusLost(evt);
            }
        });
        txtPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 56, -1));

        txtFPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPCFocusLost(evt);
            }
        });
        txtFPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtFPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 42, -1));

        txtLibrero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLibreroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLibreroFocusLost(evt);
            }
        });
        txtLibrero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibreroKeyTyped(evt);
            }
        });
        jPanel1.add(txtLibrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 56, -1));

        txtFli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFliFocusLost(evt);
            }
        });
        txtFli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFliKeyTyped(evt);
            }
        });
        jPanel1.add(txtFli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 42, -1));

        txtBote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBoteFocusLost(evt);
            }
        });
        txtBote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBoteKeyTyped(evt);
            }
        });
        jPanel1.add(txtBote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 56, -1));

        txtFBB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFBBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFBBFocusLost(evt);
            }
        });
        txtFBB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFBBKeyTyped(evt);
            }
        });
        jPanel1.add(txtFBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 42, -1));

        txtBaño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBañoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBañoFocusLost(evt);
            }
        });
        txtBaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBañoKeyTyped(evt);
            }
        });
        jPanel1.add(txtBaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 56, -1));

        txtFBA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFBAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFBAFocusLost(evt);
            }
        });
        txtFBA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFBAKeyTyped(evt);
            }
        });
        jPanel1.add(txtFBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 42, -1));

        txtUbi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUbiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUbiFocusLost(evt);
            }
        });
        txtUbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUbiKeyTyped(evt);
            }
        });
        jPanel1.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 96, -1));

        txtObser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtObserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObserFocusLost(evt);
            }
        });
        txtObser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObserKeyTyped(evt);
            }
        });
        jPanel1.add(txtObser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 96, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo (1).png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 406, -1, 30));

        txtMueble.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMuebleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMuebleFocusLost(evt);
            }
        });
        txtMueble.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMuebleKeyTyped(evt);
            }
        });
        jPanel1.add(txtMueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 281, 56, -1));

        txtFMU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMUFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMUFocusLost(evt);
            }
        });
        txtFMU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFMUKeyTyped(evt);
            }
        });
        jPanel1.add(txtFMU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 42, -1));

        txtImpresora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtImpresoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtImpresoraFocusLost(evt);
            }
        });
        txtImpresora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImpresoraKeyTyped(evt);
            }
        });
        jPanel1.add(txtImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 312, 56, -1));

        txtFI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFIFocusLost(evt);
            }
        });
        txtFI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFIKeyTyped(evt);
            }
        });
        jPanel1.add(txtFI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 42, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 406, -1, 30));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 406, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 406, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setText("Func:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("Func:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel8.setText("Func:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel9.setText("Func:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("Func:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel11.setText("Func:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel12.setText("Func:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel13.setText("Func:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel14.setText("Func:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel18.setText("Área:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 46, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setText("PC:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel4.setText("Mesa:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel19.setText("Piza:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 72, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel20.setText("Silla:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setText("Lib:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel15.setText("Bote:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel16.setText("Baño:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel17.setText("Mueb:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 282, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel21.setText("Imp:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 313, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel22.setText("Ubi:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 345, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel23.setText("Notas:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 376, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIRECTIVOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblJefes.setBackground(new java.awt.Color(153, 153, 255));
        tblJefes.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tblJefes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "AREA", "Mesa", "Silla", "PC", "Libre", "BoteB", "Baño"
            }
        ));
        tblJefes.setSelectionBackground(new java.awt.Color(255, 102, 255));
        tblJefes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJefesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJefes);

        txtBuscarSalon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusLost(evt);
            }
        });
        txtBuscarSalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarSalonKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (3).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        habilitar(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtIdJeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdJeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdJeKeyTyped

    private void txtCodigoJeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoJeKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtCodigoJeKeyTyped

    private void txtPizarronKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPizarronKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPizarronKeyTyped

    private void txtFPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPKeyTyped

    private void txtMesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtMesaKeyTyped

    private void txtFMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFMKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFMKeyTyped

    private void txtSillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSillaKeyTyped
  char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtSillaKeyTyped

    private void txtFSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFSKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFSKeyTyped

    private void txtPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPCKeyTyped

    private void txtFPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPCKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPCKeyTyped

    /*
    txtId.setText("Ingrese su ID");
        txtNombre.setText("Ingrese su Nombre");
        txtUsuario.setText("Ingrese su Usuario");
        txtnFicha.setText("Ingrese su N.Ficha");
        txtnControl.setText("Ingrese su N.Control");
        txtCarrera.setText("Ingrese su Carrera");
        txtTurno.setText("Ingrese su Turno");
        txtPuesto.setText("Ingrese su Puesto");
        txtInstitucion.setText("Ingrese su Institución");
        txtEscuela.setText("Ingrese su Escuela");
        txtClave.setText("Ingrese su Clave");
        txtConfirmarClave.setText("Confirme su Clave");
        txtBuscar.setText("Ingrese el ID");
    */
    
    private void txtIdJeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdJeFocusGained
      if(txtIdJe.getText().equals("Ingrese su ID")){
         txtIdJe.setText(null);
         txtIdJe.requestFocus();
         deleteplaceholder(txtIdJe);
      //Ingrese el ID   
     }
    }//GEN-LAST:event_txtIdJeFocusGained

    private void txtIdJeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdJeFocusLost
          if(txtIdJe.getText().length()==0){
          addplaceholder(txtIdJe);
          txtIdJe.setText("Ingrese su ID");
      }
    }//GEN-LAST:event_txtIdJeFocusLost

    private void txtCodigoJeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoJeFocusGained
        if(txtCodigoJe.getText().equals("Ingrese el Salón")){
         txtCodigoJe.setText(null);
         txtCodigoJe.requestFocus();
         deleteplaceholder(txtCodigoJe);
       
     }
    }//GEN-LAST:event_txtCodigoJeFocusGained

    private void txtCodigoJeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoJeFocusLost
        if(txtCodigoJe.getText().length()==0){
          addplaceholder(txtCodigoJe);
          txtCodigoJe.setText("Ingrese el Salón");
      }
    }//GEN-LAST:event_txtCodigoJeFocusLost

    private void txtPizarronFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPizarronFocusGained
       if(txtPizarron.getText().equals("Cantidad de Pizarrones")){
         txtPizarron.setText(null);
         txtPizarron.requestFocus();
         deleteplaceholder(txtPizarron);
      
     }
    }//GEN-LAST:event_txtPizarronFocusGained

    private void txtPizarronFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPizarronFocusLost
        if(txtPizarron.getText().length()==0){
          addplaceholder(txtPizarron);
          txtPizarron.setText("Cantidad de Pizarrones");
      }
    }//GEN-LAST:event_txtPizarronFocusLost

    private void txtFPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPFocusGained
      if(txtFP.getText().equals("Funciona")){
         txtFP.setText(null);
         txtFP.requestFocus();
         deleteplaceholder(txtFP);
       }
    }//GEN-LAST:event_txtFPFocusGained

    private void txtFPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPFocusLost
        if(txtFP.getText().length()==0){
          addplaceholder(txtFP);
          txtFP.setText("Funciona");
      }
    }//GEN-LAST:event_txtFPFocusLost

    private void txtMesaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusGained
        if(txtMesa.getText().equals("Cantidad de Sillas")){
         txtMesa.setText(null);
         txtMesa.requestFocus();
         deleteplaceholder(txtMesa);
      }
    }//GEN-LAST:event_txtMesaFocusGained

    private void txtMesaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusLost
       if(txtMesa.getText().length()==0){
          addplaceholder(txtMesa);
          txtMesa.setText("Cantidad de Sillas");
      }
    }//GEN-LAST:event_txtMesaFocusLost

    private void txtFMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusGained
       if(txtFM.getText().equals("Funciona")){
         txtFM.setText(null);
         txtFM.requestFocus();
         deleteplaceholder(txtFM);
     }
    }//GEN-LAST:event_txtFMFocusGained

    private void txtFMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusLost
         if(txtFM.getText().length()==0){
          addplaceholder(txtFM);
          txtFM.setText("Funciona");
      }
    }//GEN-LAST:event_txtFMFocusLost

    private void txtSillaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusGained
      if(txtSilla.getText().equals("Cantidad de Mesas")){
         txtSilla.setText(null);
         txtSilla.requestFocus();
         deleteplaceholder(txtSilla);
     }
    }//GEN-LAST:event_txtSillaFocusGained

    private void txtSillaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusLost
        if(txtSilla.getText().length()==0){
          addplaceholder(txtSilla);
          txtSilla.setText("Cantidad de Mesas");
      }
    }//GEN-LAST:event_txtSillaFocusLost

    private void txtFSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusGained
      if(txtFS.getText().equals("Funciona")){
         txtFS.setText(null);
         txtFS.requestFocus();
         deleteplaceholder(txtFS);
     }
    }//GEN-LAST:event_txtFSFocusGained

    private void txtFSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusLost
       if(txtFS.getText().length()==0){
          addplaceholder(txtFS);
          txtFS.setText("Funciona");
      }
    }//GEN-LAST:event_txtFSFocusLost

    private void txtPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusGained
        if(txtPC.getText().equals("Cantidad de PC")){
         txtPC.setText(null);
         txtPC.requestFocus();
         deleteplaceholder(txtPC);
     }
    }//GEN-LAST:event_txtPCFocusGained

    private void txtPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusLost
        if(txtPC.getText().length()==0){
          addplaceholder(txtPC);
          txtPC.setText("Cantidad de PC");
      }
    }//GEN-LAST:event_txtPCFocusLost

    private void txtFPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusGained
     if(txtFPC.getText().equals("Funciona")){
         txtFPC.setText(null);
         txtFPC.requestFocus();
         deleteplaceholder(txtFPC);
     }
    }//GEN-LAST:event_txtFPCFocusGained

    private void txtFPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusLost
        if(txtFPC.getText().length()==0){
          addplaceholder(txtFPC);
          txtFPC.setText("Funciona");
      }
    }//GEN-LAST:event_txtFPCFocusLost

    private void txtPizarronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPizarronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPizarronActionPerformed

    private void txtLibreroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibreroFocusGained
       if(txtLibrero.getText().equals("Cantidad de Proyectores")){
         txtLibrero.setText(null);
         txtLibrero.requestFocus();
         deleteplaceholder(txtLibrero);
     }
    }//GEN-LAST:event_txtLibreroFocusGained

    private void txtLibreroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibreroFocusLost
        if(txtLibrero.getText().length()==0){
          addplaceholder(txtLibrero);
          txtLibrero.setText("Cantidad de Proyectores");
      }
    }//GEN-LAST:event_txtLibreroFocusLost

    private void txtLibreroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibreroKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtLibreroKeyTyped

    private void txtFliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFliFocusGained
        if(txtFli.getText().equals("Funciona")){
         txtFli.setText(null);
         txtFli.requestFocus();
         deleteplaceholder(txtFli);
     }
    }//GEN-LAST:event_txtFliFocusGained

    private void txtFliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFliFocusLost
       if(txtFli.getText().length()==0){
          addplaceholder(txtFli);
          txtFli.setText("Funciona");
      }
    }//GEN-LAST:event_txtFliFocusLost

    private void txtFliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFliKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFliKeyTyped

    private void txtBoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusGained
        if(txtBote.getText().equals("Cantidad de Botes")){
         txtBote.setText(null);
         txtBote.requestFocus();
         deleteplaceholder(txtBote);
     }
    }//GEN-LAST:event_txtBoteFocusGained

    private void txtBoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusLost
        if(txtBote.getText().length()==0){
          addplaceholder(txtBote);
          txtBote.setText("Cantidad de Botes");
      }
    }//GEN-LAST:event_txtBoteFocusLost

    private void txtBoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoteKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBoteKeyTyped

    private void txtFBBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusGained
          if(txtFBB.getText().equals("Funciona")){
         txtFBB.setText(null);
         txtFBB.requestFocus();
         deleteplaceholder(txtFBB);
     }
    }//GEN-LAST:event_txtFBBFocusGained

    private void txtFBBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusLost
       if(txtFBB.getText().length()==0){
          addplaceholder(txtFBB);
          txtFBB.setText("Funciona");
      }
    }//GEN-LAST:event_txtFBBFocusLost

    private void txtFBBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFBBKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFBBKeyTyped

    private void txtBañoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBañoFocusGained
        if(txtBaño.getText().equals("Cantidad de Mesabancos")){
         txtBaño.setText(null);
         txtBaño.requestFocus();
         deleteplaceholder(txtBaño);
     }
    }//GEN-LAST:event_txtBañoFocusGained

    private void txtBañoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBañoFocusLost
        if(txtBaño.getText().length()==0){
          addplaceholder(txtBaño);
          txtBaño.setText("Cantidad de Mesabancos");
      }
    }//GEN-LAST:event_txtBañoFocusLost

    private void txtBañoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBañoKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBañoKeyTyped

    private void txtFBAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBAFocusGained
         if(txtFBA.getText().equals("Funciona")){
         txtFBA.setText(null);
         txtFBA.requestFocus();
         deleteplaceholder(txtFBA);
     }
    }//GEN-LAST:event_txtFBAFocusGained

    private void txtFBAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBAFocusLost
       if(txtFBA.getText().length()==0){
          addplaceholder(txtFBA);
          txtFBA.setText("Funciona");
      }
    }//GEN-LAST:event_txtFBAFocusLost

    private void txtFBAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFBAKeyTyped
       char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFBAKeyTyped

    private void txtUbiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusGained
            if(txtUbi.getText().equals("Ingrese la Ubicación")){
         txtUbi.setText(null);
         txtUbi.requestFocus();
         deleteplaceholder(txtUbi);
     }
    }//GEN-LAST:event_txtUbiFocusGained

    private void txtUbiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusLost
     if(txtUbi.getText().length()==0){
          addplaceholder(txtUbi);
          txtUbi.setText("Ingrese la Ubicación");
      }
    }//GEN-LAST:event_txtUbiFocusLost

    private void txtUbiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbiKeyTyped
      
    }//GEN-LAST:event_txtUbiKeyTyped

    private void txtObserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusGained
          if(txtObser.getText().equals("Ingrese la Observación")){
         txtObser.setText(null);
         txtObser.requestFocus();
         deleteplaceholder(txtObser);
         
     }
    }//GEN-LAST:event_txtObserFocusGained

    private void txtObserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusLost
        if(txtObser.getText().length()==0){
          addplaceholder(txtObser);
          txtObser.setText("Ingrese la Observación");
      }
    }//GEN-LAST:event_txtObserFocusLost

    private void txtObserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObserKeyTyped
     
    }//GEN-LAST:event_txtObserKeyTyped

    private void txtMuebleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMuebleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMuebleFocusGained

    private void txtMuebleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMuebleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMuebleFocusLost

    private void txtMuebleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMuebleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMuebleKeyTyped

    private void txtFMUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMUFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMUFocusGained

    private void txtFMUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMUFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMUFocusLost

    private void txtFMUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFMUKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMUKeyTyped

    private void txtImpresoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImpresoraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpresoraFocusGained

    private void txtImpresoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImpresoraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpresoraFocusLost

    private void txtImpresoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImpresoraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpresoraKeyTyped

    private void txtFIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFIFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFIFocusGained

    private void txtFIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFIFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFIFocusLost

    private void txtFIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFIKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
       String msg = null;
        if (txtCodigoJe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtCodigoJe.requestFocusInWindow();
            return;
        }
        if (txtPizarron.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de pizarrones es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPizarron.requestFocusInWindow();
            return;
        }
        if(txtFP.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funciona Pizarrón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFP.requestFocusInWindow();
            return;
        }
        if(txtMesa.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtMesa.requestFocusInWindow();
            return;
        }
        if(txtFM.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFM.requestFocusInWindow();
            return;
        }
        if(txtSilla.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtSilla.requestFocusInWindow();
            return;
        }
        if(txtFS.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFS.requestFocusInWindow();
            return;
        }
        if(txtPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPC.requestFocusInWindow();
            return;
        }
        if(txtFPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFPC.requestFocusInWindow();
            return;
        }
        if(txtLibrero.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Proyectores es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtLibrero.requestFocusInWindow();
            return;
        }
        if(txtFli.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Proyectores es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFli.requestFocusInWindow();
            return;
        }
        if(txtBote.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBote.requestFocusInWindow();
            return;
        }
        if(txtFBB.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBB.requestFocusInWindow();
            return;
        }
        if(txtBaño.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBaño.requestFocusInWindow();
            return;
        }
        if(txtFBA.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBA.requestFocusInWindow();
            return;
        }
        if(txtMueble.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBaño.requestFocusInWindow();
            return;
        }
        if(txtFMU.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBA.requestFocusInWindow();
            return;
        } if(txtImpresora.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBaño.requestFocusInWindow();
            return;
        }
        if(txtFI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBA.requestFocusInWindow();
            return;
        }
        if(txtUbi.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Ubicación de Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtUbi.requestFocusInWindow();
            return;
        }
        if(txtObser.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Observación de Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtUbi.requestFocusInWindow();
            return;
        }
         if (txtIdJe.getText().equals("")) {
            JefesDto jefDto = new JefesDto();
            JefesDao jefDao = new JefesDao();

            
// jefes (id_je,codigoJ,pizarron,fp,mesa,fm,silla,fs,pc,fpc,librero,fli,boteBa,fbb,baño,fba,mueble,fmu,impresora,fi,ubi,obser)

            jefDto.setCodigoJ(txtCodigoJe.getText());
            jefDto.setPizarron(txtPizarron.getText());
            jefDto.setFp(txtFP.getText());
            jefDto.setMesa(txtMesa.getText());
            jefDto.setFm(txtFM.getText());
            jefDto.setSilla(txtSilla.getText());
            jefDto.setFs(txtFS.getText());
            jefDto.setPc(txtPC.getText());
            jefDto.setFpc(txtFPC.getText());
            jefDto.setLibrero(txtLibrero.getText());
            jefDto.setFli(txtFli.getText());
            jefDto.setBoteBa(txtBote.getText());
            jefDto.setFbb(txtFBB.getText());
            jefDto.setBaño(txtBaño.getText());
            jefDto.setFba(txtFBA.getText());
            jefDto.setMueble(txtMueble.getText());
            jefDto.setFmu(txtFMU.getText());
            jefDto.setImpresora(txtImpresora.getText());
            jefDto.setFi(txtFI.getText());
            jefDto.setUbi(txtUbi.getText());
            jefDto.setObser(txtObser.getText());
                    
                    
            msg = jefDao.insertarJefes(jefDto);
                   
            JOptionPane.showMessageDialog(rootPane, msg, "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
             JefesDto jefDto = new JefesDto();
            JefesDao jefDao = new JefesDao();

          

           jefDto.setId_je(Integer.parseInt(txtIdJe.getText()));
           jefDto.setCodigoJ(txtCodigoJe.getText());
            jefDto.setPizarron(txtPizarron.getText());
            jefDto.setFp(txtFP.getText());
            jefDto.setMesa(txtMesa.getText());
            jefDto.setFm(txtFM.getText());
            jefDto.setSilla(txtSilla.getText());
            jefDto.setFs(txtFS.getText());
            jefDto.setPc(txtPC.getText());
            jefDto.setFpc(txtFPC.getText());
            jefDto.setLibrero(txtLibrero.getText());
            jefDto.setFli(txtFli.getText());
            jefDto.setBoteBa(txtBote.getText());
            jefDto.setFbb(txtFBB.getText());
            jefDto.setBaño(txtBaño.getText());
            jefDto.setFba(txtFBA.getText());
            jefDto.setMueble(txtMueble.getText());
            jefDto.setFmu(txtFMU.getText());
            jefDto.setImpresora(txtImpresora.getText());
            jefDto.setFi(txtFI.getText());
            jefDto.setUbi(txtUbi.getText());
            jefDto.setObser(txtObser.getText());
            msg = jefDao.editarJefes(jefDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
       limpiar();
        habilitar(true);
        mostrarBuscar("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
        mostrarBuscar("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String msg = null;
        if (txtIdJe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un registro de la tabla para eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {

            JefesDto jefDto = new JefesDto();
            JefesDao jefDao = new JefesDao();

            jefDto.setId_je(Integer.parseInt(txtIdJe.getText()));
            msg= jefDao.eliminarUsuarios(jefDto);

            JOptionPane.showMessageDialog(rootPane, msg, "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        mostrarBuscar("");
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        mostrarBuscar(txtBuscarSalon.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarSalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSalonKeyTyped

    }//GEN-LAST:event_txtBuscarSalonKeyTyped

    private void txtBuscarSalonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusLost
        if(txtBuscarSalon.getText().length()==0){
            addplaceholder(txtBuscarSalon);
            txtBuscarSalon.setText("Ingrese el Salón");
        }
    }//GEN-LAST:event_txtBuscarSalonFocusLost

    private void txtBuscarSalonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusGained
        if(txtBuscarSalon.getText().equals("Ingrese el Salón")){
            txtBuscarSalon.setText(null);
            txtBuscarSalon.requestFocus();
            deleteplaceholder(txtBuscarSalon);

        }
    }//GEN-LAST:event_txtBuscarSalonFocusGained

    private void tblJefesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJefesMouseClicked
        // TODO add your handling code here:
        int fila = tblJefes.getSelectedRow();
        // jefes (id_je,codigoJ,pizarron,fp,mesa,fm,silla,fs,pc,fpc,librero,fli,boteBa,fbb,baño,fba,mueble,fmu,impresora,fi,ubi,obser)

        txtIdJe.setText(tblJefes.getValueAt(fila, 0).toString());
        txtCodigoJe.setText(tblJefes.getValueAt(fila, 1).toString());
        txtPizarron.setText(tblJefes.getValueAt(fila, 2).toString());
        txtFP.setText(tblJefes.getValueAt(fila, 3).toString());
        txtMesa.setText(tblJefes.getValueAt(fila, 4).toString());
        txtFM.setText(tblJefes.getValueAt(fila, 5).toString());
        txtSilla.setText(tblJefes.getValueAt(fila, 6).toString());
        txtFS.setText(tblJefes.getValueAt(fila, 7).toString());
        txtPC.setText(tblJefes.getValueAt(fila, 8).toString());
        txtFPC.setText(tblJefes.getValueAt(fila, 9).toString());
        txtLibrero.setText(tblJefes.getValueAt(fila, 10).toString());
        txtFli.setText(tblJefes.getValueAt(fila, 11).toString());
        txtBote.setText(tblJefes.getValueAt(fila, 12).toString());
        txtFBB.setText(tblJefes.getValueAt(fila, 13).toString());
        txtBaño.setText(tblJefes.getValueAt(fila, 14).toString());
        txtFBA.setText(tblJefes.getValueAt(fila, 15).toString());
        txtMueble.setText(tblJefes.getValueAt(fila, 16).toString());
        txtFMU.setText(tblJefes.getValueAt(fila, 17).toString());
        txtImpresora.setText(tblJefes.getValueAt(fila, 18).toString());
        txtFI.setText(tblJefes.getValueAt(fila, 19).toString());
        txtUbi.setText(tblJefes.getValueAt(fila, 20).toString());
        txtObser.setText(tblJefes.getValueAt(fila, 21).toString());

    }//GEN-LAST:event_tblJefesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJefes;
    private javax.swing.JTextField txtBaño;
    private javax.swing.JTextField txtBote;
    private javax.swing.JTextField txtBuscarSalon;
    private javax.swing.JTextField txtCodigoJe;
    private javax.swing.JTextField txtFBA;
    private javax.swing.JTextField txtFBB;
    private javax.swing.JTextField txtFI;
    private javax.swing.JTextField txtFM;
    private javax.swing.JTextField txtFMU;
    private javax.swing.JTextField txtFP;
    private javax.swing.JTextField txtFPC;
    private javax.swing.JTextField txtFS;
    private javax.swing.JTextField txtFli;
    private javax.swing.JTextField txtIdJe;
    private javax.swing.JTextField txtImpresora;
    private javax.swing.JTextField txtLibrero;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtMueble;
    private javax.swing.JTextField txtObser;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPizarron;
    private javax.swing.JTextField txtSilla;
    private javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables

}
