
package IMPORTANTE;

import DTOS.JefesDto;
import DAOS.JefesDao;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
public class Jefes2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmUsuarios
     */
    public Jefes2() {
        initComponents();
        
        mostrarBuscar("");
        
        
   
       
    }
    
    
    public void addplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
       
    }
    public void deleteplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public void mostrarBuscar(String salon) {
        DefaultTableModel miModelo;
        JefesDao jefDao = new JefesDao();
        JefesDto jefDto = new JefesDto();
        jefDto.setCodigoJ(salon);
        miModelo = jefDao.mostrarJefes(jefDto);
        tblJefes.setModel(miModelo);

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJefes = new javax.swing.JTable();
        txtBuscarSalon = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(909, 480));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIRECTIVOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblJefes.setBackground(new java.awt.Color(153, 153, 255));
        tblJefes.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tblJefes.setForeground(new java.awt.Color(0, 0, 0));
        tblJefes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "AREA", "Mesa", "Silla", "PC", "Libre", "BoteB", "Baño"
            }
        ));
        tblJefes.setSelectionBackground(new java.awt.Color(255, 102, 255));
        tblJefes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblJefes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJefesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJefes);

        txtBuscarSalon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusLost(evt);
            }
        });
        txtBuscarSalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarSalonKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblJefesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJefesMouseClicked
        // TODO add your handling code here:
        int fila = tblJefes.getSelectedRow();
        // jefes (id_je,codigoJ,pizarron,fp,mesa,fm,silla,fs,pc,fpc,librero,fli,boteBa,fbb,baño,fba,mueble,fmu,impresora,fi,ubi,obser)

        
        
                
    }//GEN-LAST:event_tblJefesMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        mostrarBuscar(txtBuscarSalon.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarSalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSalonKeyTyped
         
    }//GEN-LAST:event_txtBuscarSalonKeyTyped

    private void txtBuscarSalonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusGained
       if(txtBuscarSalon.getText().equals("Ingrese el Salón")){
         txtBuscarSalon.setText(null);
         txtBuscarSalon.requestFocus();
         deleteplaceholder(txtBuscarSalon);
        
        
     }
    }//GEN-LAST:event_txtBuscarSalonFocusGained

    private void txtBuscarSalonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusLost
        if(txtBuscarSalon.getText().length()==0){
          addplaceholder(txtBuscarSalon);
          txtBuscarSalon.setText("Ingrese el Salón");
      }
    }//GEN-LAST:event_txtBuscarSalonFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJefes;
    private javax.swing.JTextField txtBuscarSalon;
    // End of variables declaration//GEN-END:variables

}
