
package IMPORTANTE;

import DTOS.SalasDto;
import DAOS.SalasDao;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class Salas extends javax.swing.JInternalFrame {

    
    public Salas() {
        initComponents();
        txtIdSalas.setVisible(false);
        txtIdSalas.setEnabled(false);
        limpiar();
        habilitar(true);
        mostrarBuscar("");
        
         
    }
    
    
    public void addplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
       
    }
    public void deleteplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public void mostrarBuscar(String salon) {
        DefaultTableModel miModelo;
        SalasDao salasDao = new SalasDao();
        SalasDto salDto = new SalasDto();
        salDto.setCodSal(salon);
        miModelo = salasDao.mostrarSalas(salDto);
        tblSalas.setModel(miModelo);

    }

    public void limpiar() {
        txtIdSalas.setText("");
        txtCodigoSalas.setText("");
        txtPizarron.setText("");
        txtFP.setText("");
        txtSilla.setText("");
        txtFS.setText("");
        txtMesa.setText("");
        txtFM.setText("");
        txtPC.setText("");
        txtFPC.setText("");
        txtProyec.setText("");
        txtFPRO.setText("");
        txtLibrero.setText("");
        txtFLIB.setText("");
        txtBote.setText("");
        txtFBB.setText("");
        txtMicroo.setText("");
        txtFMIC.setText("");
        txtCafet.setText("");
        txtFCAF.setText("");
        txtTv.setText("");
        txtFTV.setText("");
        txtRefri.setText("");
        txtFREF.setText("");
        txtGAgua.setText("");
        txtFAG.setText("");
        txtUbi.setText("");
        txtObser.setText("");
        txtBuscarSalon.setText("");
    }

    public void habilitar(boolean b) {
        txtCodigoSalas.setEnabled(!b);
        txtPizarron.setEnabled(!b);
        txtFP.setEnabled(!b);
        txtSilla.setEnabled(!b);
        txtFS.setEnabled(!b);
        txtMesa.setEnabled(!b);
        txtFM.setEnabled(!b);
        txtPC.setEnabled(!b);
        txtFPC.setEnabled(!b);
        txtProyec.setEnabled(!b);
        txtFPRO.setEnabled(!b);
        txtLibrero.setEnabled(!b);
        txtFLIB.setEnabled(!b);
        txtBote.setEnabled(!b);
        txtFBB.setEnabled(!b);
        txtMicroo.setEnabled(!b);
        txtFMIC.setEnabled(!b);
        txtCafet.setEnabled(!b);
        txtFCAF.setEnabled(!b);
        txtTv.setEnabled(!b);
        txtFTV.setEnabled(!b);
        txtRefri.setEnabled(!b);
        txtFREF.setEnabled(!b);
        txtGAgua.setEnabled(!b);
        txtFAG.setEnabled(!b);
        txtUbi.setEnabled(!b);
        txtObser.setEnabled(!b);
      

        btnNuevo.setEnabled(b);
        btnEditar.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPizarron = new javax.swing.JTextField();
        txtCodigoSalas = new javax.swing.JTextField();
        txtIdSalas = new javax.swing.JTextField();
        txtFP = new javax.swing.JTextField();
        txtSilla = new javax.swing.JTextField();
        txtFS = new javax.swing.JTextField();
        txtMesa = new javax.swing.JTextField();
        txtFM = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtFPC = new javax.swing.JTextField();
        txtProyec = new javax.swing.JTextField();
        txtFPRO = new javax.swing.JTextField();
        txtLibrero = new javax.swing.JTextField();
        txtFLIB = new javax.swing.JTextField();
        txtBote = new javax.swing.JTextField();
        txtFBB = new javax.swing.JTextField();
        txtUbi = new javax.swing.JTextField();
        txtObser = new javax.swing.JTextField();
        txtMicroo = new javax.swing.JTextField();
        txtFMIC = new javax.swing.JTextField();
        txtCafet = new javax.swing.JTextField();
        txtFCAF = new javax.swing.JTextField();
        txtTv = new javax.swing.JTextField();
        txtFTV = new javax.swing.JTextField();
        txtRefri = new javax.swing.JTextField();
        txtFREF = new javax.swing.JTextField();
        txtGAgua = new javax.swing.JTextField();
        txtFAG = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalas = new javax.swing.JTable();
        txtBuscarSalon = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(909, 480));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPizarron.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPizarronFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPizarronFocusLost(evt);
            }
        });
        txtPizarron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPizarronActionPerformed(evt);
            }
        });
        txtPizarron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPizarronKeyTyped(evt);
            }
        });
        jPanel1.add(txtPizarron, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 55, -1));

        txtCodigoSalas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoSalasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoSalasFocusLost(evt);
            }
        });
        txtCodigoSalas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoSalasKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigoSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, -1));

        txtIdSalas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdSalasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdSalasFocusLost(evt);
            }
        });
        txtIdSalas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdSalasKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 14, 7));

        txtFP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPFocusLost(evt);
            }
        });
        txtFP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPKeyTyped(evt);
            }
        });
        jPanel1.add(txtFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 42, -1));

        txtSilla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSillaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSillaFocusLost(evt);
            }
        });
        txtSilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSillaKeyTyped(evt);
            }
        });
        jPanel1.add(txtSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 55, -1));

        txtFS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFSFocusLost(evt);
            }
        });
        txtFS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFSKeyTyped(evt);
            }
        });
        jPanel1.add(txtFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 42, -1));

        txtMesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMesaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesaFocusLost(evt);
            }
        });
        txtMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesaKeyTyped(evt);
            }
        });
        jPanel1.add(txtMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 55, -1));

        txtFM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMFocusLost(evt);
            }
        });
        txtFM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFMKeyTyped(evt);
            }
        });
        jPanel1.add(txtFM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 42, -1));

        txtPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPCFocusLost(evt);
            }
        });
        txtPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 55, -1));

        txtFPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPCFocusLost(evt);
            }
        });
        txtFPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtFPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 42, -1));

        txtProyec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProyecFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProyecFocusLost(evt);
            }
        });
        txtProyec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProyecKeyTyped(evt);
            }
        });
        jPanel1.add(txtProyec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 55, -1));

        txtFPRO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPROFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPROFocusLost(evt);
            }
        });
        txtFPRO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPROKeyTyped(evt);
            }
        });
        jPanel1.add(txtFPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 42, -1));

        txtLibrero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLibreroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLibreroFocusLost(evt);
            }
        });
        txtLibrero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibreroKeyTyped(evt);
            }
        });
        jPanel1.add(txtLibrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 55, -1));

        txtFLIB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFLIBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFLIBFocusLost(evt);
            }
        });
        txtFLIB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFLIBKeyTyped(evt);
            }
        });
        jPanel1.add(txtFLIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 42, -1));

        txtBote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBoteFocusLost(evt);
            }
        });
        txtBote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBoteKeyTyped(evt);
            }
        });
        jPanel1.add(txtBote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 55, -1));

        txtFBB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFBBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFBBFocusLost(evt);
            }
        });
        txtFBB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFBBKeyTyped(evt);
            }
        });
        jPanel1.add(txtFBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 42, -1));

        txtUbi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUbiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUbiFocusLost(evt);
            }
        });
        txtUbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUbiKeyTyped(evt);
            }
        });
        jPanel1.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 60, 30));

        txtObser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtObserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObserFocusLost(evt);
            }
        });
        txtObser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObserKeyTyped(evt);
            }
        });
        jPanel1.add(txtObser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 40, 30));

        txtMicroo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMicrooFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMicrooFocusLost(evt);
            }
        });
        txtMicroo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMicrooKeyTyped(evt);
            }
        });
        jPanel1.add(txtMicroo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 55, -1));

        txtFMIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMICFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMICFocusLost(evt);
            }
        });
        txtFMIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFMICKeyTyped(evt);
            }
        });
        jPanel1.add(txtFMIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 42, -1));

        txtCafet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCafetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCafetFocusLost(evt);
            }
        });
        txtCafet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCafetKeyTyped(evt);
            }
        });
        jPanel1.add(txtCafet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 55, -1));

        txtFCAF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFCAFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFCAFFocusLost(evt);
            }
        });
        txtFCAF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFCAFKeyTyped(evt);
            }
        });
        jPanel1.add(txtFCAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 42, -1));

        txtTv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTvFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTvFocusLost(evt);
            }
        });
        txtTv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTvKeyTyped(evt);
            }
        });
        jPanel1.add(txtTv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 55, -1));

        txtFTV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFTVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFTVFocusLost(evt);
            }
        });
        txtFTV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFTVKeyTyped(evt);
            }
        });
        jPanel1.add(txtFTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 42, -1));

        txtRefri.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRefriFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefriFocusLost(evt);
            }
        });
        txtRefri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRefriKeyTyped(evt);
            }
        });
        jPanel1.add(txtRefri, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 55, -1));

        txtFREF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFREFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFREFFocusLost(evt);
            }
        });
        txtFREF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFREFKeyTyped(evt);
            }
        });
        jPanel1.add(txtFREF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 42, -1));

        txtGAgua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGAguaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGAguaFocusLost(evt);
            }
        });
        txtGAgua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGAguaKeyTyped(evt);
            }
        });
        jPanel1.add(txtGAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 55, -1));

        txtFAG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFAGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFAGFocusLost(evt);
            }
        });
        txtFAG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFAGKeyTyped(evt);
            }
        });
        jPanel1.add(txtFAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 42, 20));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo (1).png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 52, 30));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setText("Func:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("Func:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel8.setText("Func:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel9.setText("Func:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("Func:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel11.setText("Func:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel12.setText("Func:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel13.setText("Func:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel14.setText("Func:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel16.setText("Func:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel17.setText("Func:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel18.setText("Func:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel15.setText("Salas:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setText("Silla:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel19.setText("Mesa:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel20.setText("PC:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel21.setText("Notas:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel4.setText("Pizar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel22.setText("Proye:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel23.setText("Lib:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel24.setText("Bote:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel25.setText("Micro:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel26.setText("Cafet:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel27.setText("Tv:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel28.setText("Refri:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel29.setText("GAgua:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel30.setText("Ubi:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblSalas.setBackground(new java.awt.Color(153, 153, 255));
        tblSalas.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tblSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "USUARIO", "NFicha", "NControl", "Carrera", "Turno", "Puesto", "Institucion", "Escuela", "PERFIL"
            }
        ));
        tblSalas.setSelectionBackground(new java.awt.Color(255, 102, 255));
        tblSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSalas);

        txtBuscarSalon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusLost(evt);
            }
        });
        txtBuscarSalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarSalonKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (3).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        habilitar(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalasMouseClicked
        // TODO add your handling code here:
        int fila = tblSalas.getSelectedRow();
//salas(id_Sa,codSa,pizar,fp,silla,fs,mesa,fm,pc,fpc,proyec,fpro,lib,fli,boteBa,fbb,microo,fmic,cafet,fcaf,tv,ftv,refri,fref,gAgua,fag,ubi,obser )

        txtIdSalas.setText(tblSalas.getValueAt(fila, 0).toString());
        txtCodigoSalas.setText(tblSalas.getValueAt(fila, 1).toString());
        txtPizarron.setText(tblSalas.getValueAt(fila, 2).toString());
        txtFP.setText(tblSalas.getValueAt(fila, 3).toString());
        txtSilla.setText(tblSalas.getValueAt(fila, 4).toString());
        txtFS.setText(tblSalas.getValueAt(fila, 5).toString());
        txtMesa.setText(tblSalas.getValueAt(fila, 6).toString());
        txtFM.setText(tblSalas.getValueAt(fila, 7).toString());
        txtPC.setText(tblSalas.getValueAt(fila, 8).toString());
        txtFPC.setText(tblSalas.getValueAt(fila, 9).toString());
        txtProyec.setText(tblSalas.getValueAt(fila, 10).toString());
        txtFPRO.setText(tblSalas.getValueAt(fila, 11).toString());
        txtLibrero.setText(tblSalas.getValueAt(fila, 12).toString());
        txtFLIB.setText(tblSalas.getValueAt(fila, 13).toString());
        txtBote.setText(tblSalas.getValueAt(fila, 14).toString());
        txtFBB.setText(tblSalas.getValueAt(fila, 15).toString());
        txtMicroo.setText(tblSalas.getValueAt(fila, 16).toString());
        txtFMIC.setText(tblSalas.getValueAt(fila, 17).toString());
        txtCafet.setText(tblSalas.getValueAt(fila, 18).toString());
        txtFCAF.setText(tblSalas.getValueAt(fila, 19).toString());
        txtTv.setText(tblSalas.getValueAt(fila, 20).toString());
        txtFTV.setText(tblSalas.getValueAt(fila, 21).toString());
        txtRefri.setText(tblSalas.getValueAt(fila, 22).toString());
        txtFREF.setText(tblSalas.getValueAt(fila, 23).toString());
        txtGAgua.setText(tblSalas.getValueAt(fila, 24).toString());
        txtFAG.setText(tblSalas.getValueAt(fila, 25).toString());
        txtUbi.setText(tblSalas.getValueAt(fila, 26).toString());
        txtObser.setText(tblSalas.getValueAt(fila, 27).toString());
        
                
    }//GEN-LAST:event_tblSalasMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        mostrarBuscar(txtBuscarSalon.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIdSalasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSalasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSalasKeyTyped

    private void txtCodigoSalasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoSalasKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtCodigoSalasKeyTyped

    private void txtPizarronKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPizarronKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPizarronKeyTyped

    private void txtFPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPKeyTyped

    private void txtSillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSillaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtSillaKeyTyped

    private void txtFSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFSKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFSKeyTyped

    private void txtMesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesaKeyTyped
  char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtMesaKeyTyped

    private void txtFMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFMKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFMKeyTyped

    private void txtPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPCKeyTyped

    private void txtFPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPCKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPCKeyTyped

    /*
    txtId.setText("Ingrese su ID");
        txtNombre.setText("Ingrese su Nombre");
        txtUsuario.setText("Ingrese su Usuario");
        txtnFicha.setText("Ingrese su N.Ficha");
        txtnControl.setText("Ingrese su N.Control");
        txtCarrera.setText("Ingrese su Carrera");
        txtTurno.setText("Ingrese su Turno");
        txtPuesto.setText("Ingrese su Puesto");
        txtInstitucion.setText("Ingrese su Institución");
        txtEscuela.setText("Ingrese su Escuela");
        txtClave.setText("Ingrese su Clave");
        txtConfirmarClave.setText("Confirme su Clave");
        txtBuscar.setText("Ingrese el ID");
    */
    
    private void txtIdSalasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdSalasFocusGained
      if(txtIdSalas.getText().equals("Ingrese su ID")){
         txtIdSalas.setText(null);
         txtIdSalas.requestFocus();
         deleteplaceholder(txtIdSalas);
      //Ingrese el ID   
     }
    }//GEN-LAST:event_txtIdSalasFocusGained

    private void txtIdSalasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdSalasFocusLost
          if(txtIdSalas.getText().length()==0){
          addplaceholder(txtIdSalas);
          txtIdSalas.setText("Ingrese su ID");
      }
    }//GEN-LAST:event_txtIdSalasFocusLost

    private void txtCodigoSalasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoSalasFocusGained
        if(txtCodigoSalas.getText().equals("Ingrese el Salón")){
         txtCodigoSalas.setText(null);
         txtCodigoSalas.requestFocus();
         deleteplaceholder(txtCodigoSalas);
       
     }
    }//GEN-LAST:event_txtCodigoSalasFocusGained

    private void txtCodigoSalasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoSalasFocusLost
        
    }//GEN-LAST:event_txtCodigoSalasFocusLost

    private void txtPizarronFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPizarronFocusGained
       
    }//GEN-LAST:event_txtPizarronFocusGained

    private void txtPizarronFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPizarronFocusLost
    }//GEN-LAST:event_txtPizarronFocusLost

    private void txtFPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPFocusGained
    }//GEN-LAST:event_txtFPFocusGained

    private void txtFPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPFocusLost
    }//GEN-LAST:event_txtFPFocusLost

    private void txtSillaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusGained
    }//GEN-LAST:event_txtSillaFocusGained

    private void txtSillaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusLost
    }//GEN-LAST:event_txtSillaFocusLost

    private void txtFSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusGained
    }//GEN-LAST:event_txtFSFocusGained

    private void txtFSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusLost
    }//GEN-LAST:event_txtFSFocusLost

    private void txtMesaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusGained
    }//GEN-LAST:event_txtMesaFocusGained

    private void txtMesaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusLost
    }//GEN-LAST:event_txtMesaFocusLost

    private void txtFMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusGained

    }//GEN-LAST:event_txtFMFocusGained

    private void txtFMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusLost
    }//GEN-LAST:event_txtFMFocusLost

    private void txtPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusGained
    }//GEN-LAST:event_txtPCFocusGained

    private void txtPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusLost
    }//GEN-LAST:event_txtPCFocusLost

    private void txtFPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusGained
    }//GEN-LAST:event_txtFPCFocusGained

    private void txtFPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusLost
    }//GEN-LAST:event_txtFPCFocusLost

    private void txtBuscarSalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSalonKeyTyped
         
    }//GEN-LAST:event_txtBuscarSalonKeyTyped

    private void txtBuscarSalonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusGained
        
    }//GEN-LAST:event_txtBuscarSalonFocusGained

    private void txtBuscarSalonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusLost
        if(txtBuscarSalon.getText().length()==0){
          addplaceholder(txtBuscarSalon);
          txtBuscarSalon.setText("Ingrese el Salón");
      }
    }//GEN-LAST:event_txtBuscarSalonFocusLost

    private void txtPizarronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPizarronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPizarronActionPerformed

    private void txtProyecFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProyecFocusGained
     
    }//GEN-LAST:event_txtProyecFocusGained

    private void txtProyecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProyecFocusLost
     
    }//GEN-LAST:event_txtProyecFocusLost

    private void txtProyecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProyecKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtProyecKeyTyped

    private void txtFPROFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPROFocusGained
     
    }//GEN-LAST:event_txtFPROFocusGained

    private void txtFPROFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPROFocusLost
     
    }//GEN-LAST:event_txtFPROFocusLost

    private void txtFPROKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPROKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPROKeyTyped

    private void txtLibreroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibreroFocusGained
     
    }//GEN-LAST:event_txtLibreroFocusGained

    private void txtLibreroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibreroFocusLost
     
    }//GEN-LAST:event_txtLibreroFocusLost

    private void txtLibreroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibreroKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtLibreroKeyTyped

    private void txtFLIBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFLIBFocusGained
    }//GEN-LAST:event_txtFLIBFocusGained

    private void txtFLIBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFLIBFocusLost
    }//GEN-LAST:event_txtFLIBFocusLost

    private void txtFLIBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFLIBKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFLIBKeyTyped

    private void txtBoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusGained
    }//GEN-LAST:event_txtBoteFocusGained

    private void txtBoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusLost
    }//GEN-LAST:event_txtBoteFocusLost

    private void txtBoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoteKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBoteKeyTyped

    private void txtFBBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusGained
    }//GEN-LAST:event_txtFBBFocusGained

    private void txtFBBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusLost
    }//GEN-LAST:event_txtFBBFocusLost

    private void txtFBBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFBBKeyTyped
       char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFBBKeyTyped

    private void txtUbiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusGained
    }//GEN-LAST:event_txtUbiFocusGained

    private void txtUbiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusLost
    }//GEN-LAST:event_txtUbiFocusLost

    private void txtUbiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbiKeyTyped
      
    }//GEN-LAST:event_txtUbiKeyTyped

    private void txtObserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusGained
    }//GEN-LAST:event_txtObserFocusGained

    private void txtObserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusLost
    }//GEN-LAST:event_txtObserFocusLost

    private void txtObserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObserKeyTyped
     
    }//GEN-LAST:event_txtObserKeyTyped

    private void txtMicrooFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMicrooFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMicrooFocusGained

    private void txtMicrooFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMicrooFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMicrooFocusLost

    private void txtMicrooKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMicrooKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMicrooKeyTyped

    private void txtFMICFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMICFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMICFocusGained

    private void txtFMICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMICFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMICFocusLost

    private void txtFMICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFMICKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMICKeyTyped

    private void txtCafetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCafetFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafetFocusGained

    private void txtCafetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCafetFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafetFocusLost

    private void txtCafetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCafetKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafetKeyTyped

    private void txtFCAFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCAFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCAFFocusGained

    private void txtFCAFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCAFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCAFFocusLost

    private void txtFCAFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFCAFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCAFKeyTyped

    private void txtTvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTvFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTvFocusGained

    private void txtTvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTvFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTvFocusLost

    private void txtTvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTvKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTvKeyTyped

    private void txtFTVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFTVFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTVFocusGained

    private void txtFTVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFTVFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTVFocusLost

    private void txtFTVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFTVKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTVKeyTyped

    private void txtRefriFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefriFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefriFocusGained

    private void txtRefriFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefriFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefriFocusLost

    private void txtRefriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRefriKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefriKeyTyped

    private void txtFREFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFREFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFREFFocusGained

    private void txtFREFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFREFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFREFFocusLost

    private void txtFREFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFREFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFREFKeyTyped

    private void txtGAguaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGAguaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGAguaFocusGained

    private void txtGAguaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGAguaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGAguaFocusLost

    private void txtGAguaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGAguaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGAguaKeyTyped

    private void txtFAGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFAGFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAGFocusGained

    private void txtFAGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFAGFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAGFocusLost

    private void txtFAGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFAGKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAGKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        
        String msg = null;
        if (txtCodigoSalas.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtCodigoSalas.requestFocusInWindow();
            return;
        }
        if (txtPizarron.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de pizarrones es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPizarron.requestFocusInWindow();
            return;
        }
        if(txtFP.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funciona Pizarrón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFP.requestFocusInWindow();
            return;
        }
        if(txtSilla.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtSilla.requestFocusInWindow();
            return;
        }
        if(txtFS.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFS.requestFocusInWindow();
            return;
        }
        if(txtMesa.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtMesa.requestFocusInWindow();
            return;
        }
        if(txtFM.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFM.requestFocusInWindow();
            return;
        }
        if(txtPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPC.requestFocusInWindow();
            return;
        }
        if(txtFPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFPC.requestFocusInWindow();
            return;
        }
        if(txtProyec.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Proyectores es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtProyec.requestFocusInWindow();
            return;
        }
        if(txtFPRO.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Proyectores es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFPRO.requestFocusInWindow();
            return;
        }
        if(txtLibrero.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Libreros es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtLibrero.requestFocusInWindow();
            return;
        }
        if(txtFLIB.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Libreros es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFLIB.requestFocusInWindow();
            return;
        }
        if(txtBote.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBote.requestFocusInWindow();
            return;
        }
        if(txtFBB.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBB.requestFocusInWindow();
            return;
        }
        if(txtMicroo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Microondas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBote.requestFocusInWindow();
            return;
        }
        if(txtFMIC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Microondas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBB.requestFocusInWindow();
            return;
        }
        if(txtCafet.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Cafeteras es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBote.requestFocusInWindow();
            return;
        }
        if(txtFCAF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Cafeteras es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBB.requestFocusInWindow();
            return;
        }
        if(txtUbi.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Ubicación de Salas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtUbi.requestFocusInWindow();
            return;
        }
        
         if (txtIdSalas.getText().equals("")) {
            SalasDto salDto = new SalasDto();
            SalasDao salDao = new SalasDao();
//salas(id_Sa,codSa,pizar,fp,silla,fs,mesa,fm,pc,fpc,proyec,fpro,lib,fli,boteBa,fbb,microo,fmic,cafet,fcaf,tv,ftv,refri,fref,gAgua,fag,ubi,obser )
        
            salDto.setCodSal(txtCodigoSalas.getText());
            salDto.setPizar(txtPizarron.getText());
            salDto.setFp(txtFP.getText());
            salDto.setSilla(txtSilla.getText());
            salDto.setFs(txtFS.getText());
            salDto.setMesa(txtMesa.getText());
            salDto.setFm(txtFM.getText());
            salDto.setPc(txtPC.getText());
            salDto.setFpc(txtFPC.getText());
            salDto.setProyec(txtProyec.getText());
            salDto.setFpro(txtFPRO.getText());
            salDto.setLib(txtLibrero.getText());
            salDto.setFli(txtFLIB.getText());
            salDto.setBoteBa(txtBote.getText());
            salDto.setFbb(txtFBB.getText());
            salDto.setMicroo(txtMicroo.getText());
            salDto.setFmic(txtFMIC.getText());
            salDto.setCafet(txtCafet.getText());
            salDto.setFcaf(txtFCAF.getText());
            salDto.setTv(txtTv.getText());
            salDto.setFtv(txtFTV.getText());
            salDto.setRefri(txtRefri.getText());
            salDto.setFref(txtFREF.getText());
            salDto.setgAgua(txtGAgua.getText());
            salDto.setFag(txtFAG.getText());
            salDto.setUbi(txtUbi.getText());
            salDto.setObser(txtObser.getText());

            msg = salDao.insertarSalas2(salDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Sala Registrada", JOptionPane.INFORMATION_MESSAGE);
        } else {
          
            SalasDto salDto = new SalasDto();
            SalasDao salDao = new SalasDao();

            
//salas(id_Sa,codSa,pizar,fp,silla,fs,mesa,fm,pc,fpc,proyec,fpro,lib,fli,boteBa,fbb,microo,fmic,cafet,fcaf,tv,ftv,refri,fref,gAgua,fag,ubi,obser )

            salDto.setId_sal(Integer.parseInt(txtIdSalas.getText()));
            salDto.setCodSal(txtCodigoSalas.getText());
            salDto.setPizar(txtPizarron.getText());
            salDto.setFp(txtFP.getText());
            salDto.setSilla(txtSilla.getText());
            salDto.setFs(txtFS.getText());
            salDto.setMesa(txtMesa.getText());
            salDto.setFm(txtFM.getText());
            salDto.setPc(txtPC.getText());
            salDto.setFpc(txtFPC.getText());
            salDto.setProyec(txtProyec.getText());
            salDto.setFpro(txtFPRO.getText());
            salDto.setLib(txtLibrero.getText());
            salDto.setFli(txtFLIB.getText());
            salDto.setBoteBa(txtBote.getText());
            salDto.setFbb(txtFBB.getText());
            salDto.setMicroo(txtMicroo.getText());
            salDto.setFmic(txtFMIC.getText());
            salDto.setCafet(txtCafet.getText());
            salDto.setFcaf(txtFCAF.getText());
            salDto.setTv(txtTv.getText());
            salDto.setFtv(txtFTV.getText());
            salDto.setRefri(txtRefri.getText());
            salDto.setFref(txtFREF.getText());
            salDto.setgAgua(txtGAgua.getText());
            salDto.setFag(txtFAG.getText());
            salDto.setUbi(txtUbi.getText());
            salDto.setObser(txtObser.getText());
           
             
            msg = salDao.editarSalas(salDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Sala Actualizada", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
       limpiar();
        habilitar(true);
        mostrarBuscar("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
        mostrarBuscar("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String msg = null;
        if (txtIdSalas.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un registro de la tabla para eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            
             SalasDto salDto = new SalasDto();
            SalasDao salDao = new SalasDao();
        
        salDto.setId_sal(Integer.parseInt(txtIdSalas.getText()));
               
        msg= salDao.eliminarSalas(salDto);
        
            JOptionPane.showMessageDialog(rootPane, msg, "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        mostrarBuscar("");
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalas;
    private javax.swing.JTextField txtBote;
    private javax.swing.JTextField txtBuscarSalon;
    private javax.swing.JTextField txtCafet;
    private javax.swing.JTextField txtCodigoSalas;
    private javax.swing.JTextField txtFAG;
    private javax.swing.JTextField txtFBB;
    private javax.swing.JTextField txtFCAF;
    private javax.swing.JTextField txtFLIB;
    private javax.swing.JTextField txtFM;
    private javax.swing.JTextField txtFMIC;
    private javax.swing.JTextField txtFP;
    private javax.swing.JTextField txtFPC;
    private javax.swing.JTextField txtFPRO;
    private javax.swing.JTextField txtFREF;
    private javax.swing.JTextField txtFS;
    private javax.swing.JTextField txtFTV;
    private javax.swing.JTextField txtGAgua;
    private javax.swing.JTextField txtIdSalas;
    private javax.swing.JTextField txtLibrero;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtMicroo;
    private javax.swing.JTextField txtObser;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPizarron;
    private javax.swing.JTextField txtProyec;
    private javax.swing.JTextField txtRefri;
    private javax.swing.JTextField txtSilla;
    private javax.swing.JTextField txtTv;
    private javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables

}
