
package IMPORTANTE;

import DTOS.SalonesDto;
import DAOS.SalonesDao;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class Salones extends javax.swing.JInternalFrame {

   
    public Salones() {
        initComponents();
        txtIdSalon.setVisible(false);
        txtIdSalon.setEnabled(false);
        limpiar();
        habilitar(true);
        mostrarBuscar("");
      
    }
    
    
    public void addplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
       
    }
    public void deleteplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public void mostrarBuscar(String salon) {
        DefaultTableModel miModelo;
        SalonesDao salDao = new SalonesDao();
        SalonesDto salDto = new SalonesDto();
        salDto.setCodigoSalon(salon);
                //.setUsuario(salon);
        miModelo = salDao.mostrarSalones(salDto);
                //.mostrarUsuarios(salDto);
        tblSalones.setModel(miModelo);

    }

    public void limpiar() {
        txtIdSalon.setText("");
        txtCodigo.setText("");
        txtPizarron.setText("");
        txtF.setText("");
        txtSilla.setText("");
        txtFS.setText("");
        txtMesa.setText("");
        txtFM.setText("");
        txtPC.setText("");
        txtFPC.setText("");
        txtProyec.setText("");
        txtFPRO.setText("");
        txtBote.setText("");
        txtFBB.setText("");
        txtMesaban.setText("");
        txtFMB.setText("");
        txtClima.setText("");
        txtLuz.setText("");
        txtUbi.setText("");
        txtObser.setText("");
        txtBuscarSalon.setText("");
    }

    public void habilitar(boolean b) {
        txtCodigo.setEnabled(!b);
        txtPizarron.setEnabled(!b);
        txtF.setEnabled(!b);
        txtSilla.setEnabled(!b);
        txtFS.setEnabled(!b);
        txtMesa.setEnabled(!b);
        txtFM.setEnabled(!b);
        txtPC.setEnabled(!b);
        txtFPC.setEnabled(!b);
        txtProyec.setEnabled(!b);
        txtFPRO.setEnabled(!b);
        txtBote.setEnabled(!b);
        txtFBB.setEnabled(!b);
        txtMesaban.setEnabled(!b);
        txtFMB.setEnabled(!b);
        txtClima.setEnabled(!b);
        txtLuz.setEnabled(!b);
        txtUbi.setEnabled(!b);
        txtObser.setEnabled(!b);
      

        btnNuevo.setEnabled(b);
        btnEditar.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtIdSalon = new javax.swing.JTextField();
        txtClima = new javax.swing.JTextField();
        txtLuz = new javax.swing.JTextField();
        txtUbi = new javax.swing.JTextField();
        txtObser = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPizarron = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSilla = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMesa = new javax.swing.JTextField();
        txtFM = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtFPC = new javax.swing.JTextField();
        txtProyec = new javax.swing.JTextField();
        txtFPRO = new javax.swing.JTextField();
        txtBote = new javax.swing.JTextField();
        txtFBB = new javax.swing.JTextField();
        txtMesaban = new javax.swing.JTextField();
        txtFMB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalones = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        txtBuscarSalon = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(909, 480));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, -1));

        txtIdSalon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdSalonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdSalonFocusLost(evt);
            }
        });
        txtIdSalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdSalonKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 29, 14, 7));

        txtClima.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClimaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClimaFocusLost(evt);
            }
        });
        txtClima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClimaKeyTyped(evt);
            }
        });
        jPanel1.add(txtClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 60, -1));

        txtLuz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLuzFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLuzFocusLost(evt);
            }
        });
        txtLuz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLuzKeyTyped(evt);
            }
        });
        jPanel1.add(txtLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 60, -1));

        txtUbi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUbiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUbiFocusLost(evt);
            }
        });
        txtUbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUbiKeyTyped(evt);
            }
        });
        jPanel1.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, -1));

        txtObser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtObserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObserFocusLost(evt);
            }
        });
        txtObser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObserKeyTyped(evt);
            }
        });
        jPanel1.add(txtObser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 60, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo (1).png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 401, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 401, -1, 30));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 401, -1, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 401, -1, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setText("Piza:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 74, -1, -1));

        txtPizarron.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPizarronFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPizarronFocusLost(evt);
            }
        });
        txtPizarron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPizarronActionPerformed(evt);
            }
        });
        txtPizarron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPizarronKeyTyped(evt);
            }
        });
        jPanel1.add(txtPizarron, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setText("Fun:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        txtF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFFocusLost(evt);
            }
        });
        txtF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFKeyTyped(evt);
            }
        });
        jPanel1.add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 40, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setText("Silla:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtSilla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSillaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSillaFocusLost(evt);
            }
        });
        txtSilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSillaKeyTyped(evt);
            }
        });
        jPanel1.add(txtSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 60, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setText("Notas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtFS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFSFocusLost(evt);
            }
        });
        txtFS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFSKeyTyped(evt);
            }
        });
        jPanel1.add(txtFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 40, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setText("Fun:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        txtMesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMesaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesaFocusLost(evt);
            }
        });
        txtMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesaKeyTyped(evt);
            }
        });
        jPanel1.add(txtMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 60, -1));

        txtFM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMFocusLost(evt);
            }
        });
        txtFM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFMKeyTyped(evt);
            }
        });
        jPanel1.add(txtFM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, -1));

        txtPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPCFocusLost(evt);
            }
        });
        txtPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 60, -1));

        txtFPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPCFocusLost(evt);
            }
        });
        txtFPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPCKeyTyped(evt);
            }
        });
        jPanel1.add(txtFPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 40, -1));

        txtProyec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProyecFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProyecFocusLost(evt);
            }
        });
        txtProyec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProyecKeyTyped(evt);
            }
        });
        jPanel1.add(txtProyec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 60, -1));

        txtFPRO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPROFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPROFocusLost(evt);
            }
        });
        txtFPRO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPROKeyTyped(evt);
            }
        });
        jPanel1.add(txtFPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 40, -1));

        txtBote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBoteFocusLost(evt);
            }
        });
        txtBote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBoteKeyTyped(evt);
            }
        });
        jPanel1.add(txtBote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 60, -1));

        txtFBB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFBBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFBBFocusLost(evt);
            }
        });
        txtFBB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFBBKeyTyped(evt);
            }
        });
        jPanel1.add(txtFBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 40, -1));

        txtMesaban.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMesabanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMesabanFocusLost(evt);
            }
        });
        txtMesaban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesabanKeyTyped(evt);
            }
        });
        jPanel1.add(txtMesaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 60, -1));

        txtFMB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMBFocusLost(evt);
            }
        });
        txtFMB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFMBKeyTyped(evt);
            }
        });
        jPanel1.add(txtFMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 40, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("Fun:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel8.setText("Fun:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel9.setText("Fun:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("Fun:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel11.setText("Fun:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel12.setText("Salón:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 43, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel13.setText("Mesa:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel14.setText("PC:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel15.setText("Proy:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel16.setText("Bote:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel17.setText("Mesab:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel18.setText("Luz:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel19.setText("Clima:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel20.setText("Ubi:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        tblSalones.setBackground(new java.awt.Color(153, 153, 255));
        tblSalones.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tblSalones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "USUARIO", "NFicha", "NControl", "Carrera", "Turno", "Puesto", "Institucion", "Escuela", "PERFIL"
            }
        ));
        tblSalones.setSelectionBackground(new java.awt.Color(255, 102, 255));
        tblSalones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalonesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSalones);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (3).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBuscarSalon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarSalonFocusLost(evt);
            }
        });
        txtBuscarSalon.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBuscarSalonInputMethodTextChanged(evt);
            }
        });
        txtBuscarSalon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtBuscarSalonPropertyChange(evt);
            }
        });
        txtBuscarSalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarSalonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarSalonKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        habilitar(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        String msg = null;
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtCodigo.requestFocusInWindow();
            return;
        }
        if (txtPizarron.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de pizarrones es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPizarron.requestFocusInWindow();
            return;
        }
        if(txtF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funciona Pizarrón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtF.requestFocusInWindow();
            return;
        }
        if(txtSilla.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtSilla.requestFocusInWindow();
            return;
        }
        if(txtFS.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Sillas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFS.requestFocusInWindow();
            return;
        }
        if(txtMesa.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtMesa.requestFocusInWindow();
            return;
        }
        if(txtFM.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesas es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFM.requestFocusInWindow();
            return;
        }
        if(txtPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPC.requestFocusInWindow();
            return;
        }
        if(txtFPC.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan PC es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFPC.requestFocusInWindow();
            return;
        }
        if(txtProyec.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Proyectores es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtProyec.requestFocusInWindow();
            return;
        }
        if(txtFPRO.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Proyectores es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFPRO.requestFocusInWindow();
            return;
        }
        if(txtBote.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtBote.requestFocusInWindow();
            return;
        }
        if(txtFBB.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Botes es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFBB.requestFocusInWindow();
            return;
        }
        if(txtMesaban.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Cantidad de Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtMesaban.requestFocusInWindow();
            return;
        }
        if(txtFMB.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funcionan Mesabancos es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtFMB.requestFocusInWindow();
            return;
        }
        if(txtClima.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funciona el Clima es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtClima.requestFocusInWindow();
            return;
        }
        if(txtLuz.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Funciona la Luz es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtLuz.requestFocusInWindow();
            return;
        }
        if(txtUbi.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Ubicación de Salón es obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtUbi.requestFocusInWindow();
            return;
        }

         //id_salon, codigoSalon, pizarron, f, silla, fs, mesa, fm, pc, fpc, proyector, fpro, bBasura, fbb, mesaBan, fmb, clima, luz, ubi, obser

        if (txtIdSalon.getText().equals("")) {
            SalonesDto salonesDto = new SalonesDto();
            SalonesDao salonesDao = new SalonesDao();

            salonesDto.setCodigoSalon(txtCodigo.getText());
            salonesDto.setPizarron(Integer.parseInt(txtPizarron.getText()));
            salonesDto.setF(txtF.getText());
            salonesDto.setSilla(Integer.parseInt(txtSilla.getText()));
            salonesDto.setFs(txtFS.getText());
            salonesDto.setMesa(Integer.parseInt(txtMesa.getText()));
            salonesDto.setFm(txtFM.getText());
            salonesDto.setPc(Integer.parseInt(txtPC.getText()));
            salonesDto.setFpc(txtFPC.getText());
            salonesDto.setProyector(Integer.parseInt(txtProyec.getText()));
            salonesDto.setFpro(txtFPRO.getText());
            salonesDto.setbBasura(Integer.parseInt(txtBote.getText()));
            salonesDto.setFbb(txtFBB.getText());
            salonesDto.setMesaBan(Integer.parseInt(txtMesaban.getText()));
            salonesDto.setFmb(txtFMB.getText());
            salonesDto.setClima(txtClima.getText());
            salonesDto.setLuz(txtLuz.getText());
            salonesDto.setUbi(txtUbi.getText());
            salonesDto.setObser(txtObser.getText());
                    
                    
            msg = salonesDao.insertarSalones(salonesDto);
                   
            JOptionPane.showMessageDialog(rootPane, msg, "Salón Agregado", JOptionPane.INFORMATION_MESSAGE);
          
        } else {
            
            SalonesDto salonesDto = new SalonesDto();
            SalonesDao salonesDao = new SalonesDao();

            //id_salon, codigoSalon, pizarron, f, silla, fs, mesa, fm, pc, fpc, proyector, fpro, bBasura, fbb, mesaBan, fmb, clima, luz, ubi, obser
            salonesDto.setId_salon(Integer.parseInt(txtIdSalon.getText()));
            salonesDto.setCodigoSalon(txtCodigo.getText());
            salonesDto.setPizarron(Integer.parseInt(txtPizarron.getText()));
            salonesDto.setF(txtF.getText());
            salonesDto.setSilla(Integer.parseInt(txtSilla.getText()));
            salonesDto.setFs(txtFS.getText());
            salonesDto.setMesa(Integer.parseInt(txtMesa.getText()));
            salonesDto.setFm(txtFM.getText());
            salonesDto.setPc(Integer.parseInt(txtPC.getText()));
            salonesDto.setFpc(txtFPC.getText());
            salonesDto.setProyector(Integer.parseInt(txtProyec.getText()));
            salonesDto.setFpro(txtFPRO.getText());
            salonesDto.setbBasura(Integer.parseInt(txtBote.getText()));
            salonesDto.setFbb(txtFBB.getText());
            salonesDto.setMesaBan(Integer.parseInt(txtMesaban.getText()));
            salonesDto.setFmb(txtFMB.getText());
            salonesDto.setClima(txtClima.getText());
            salonesDto.setLuz(txtLuz.getText());
            salonesDto.setUbi(txtUbi.getText());
            salonesDto.setObser(txtObser.getText());

            msg = salonesDao.editarSalones(salonesDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Salón Modificado", JOptionPane.INFORMATION_MESSAGE);
         
        }
        
        
       limpiar();
        habilitar(true);
        mostrarBuscar("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
        mostrarBuscar("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String msg = null;
        if (txtIdSalon.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un registro de la tabla para eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            
            SalonesDao salDao = new SalonesDao();
        SalonesDto salDto = new SalonesDto();
        
        salDto.setId_salon(Integer.parseInt(txtIdSalon.getText()));
        msg= salDao.eliminarUsuarios(salDto);
        
            JOptionPane.showMessageDialog(rootPane, msg, "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        mostrarBuscar("");
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblSalonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalonesMouseClicked
        // TODO add your handling code here:
        int fila = tblSalones.getSelectedRow();
        txtIdSalon.setText(tblSalones.getValueAt(fila, 0).toString());
        txtCodigo.setText(tblSalones.getValueAt(fila, 1).toString());
        txtPizarron.setText(tblSalones.getValueAt(fila, 2).toString());
        txtF.setText(tblSalones.getValueAt(fila, 3).toString());
        txtSilla.setText(tblSalones.getValueAt(fila, 4).toString());
        txtFS.setText(tblSalones.getValueAt(fila, 5).toString());
        txtMesa.setText(tblSalones.getValueAt(fila, 6).toString());
        txtFM.setText(tblSalones.getValueAt(fila, 7).toString());
        txtPC.setText(tblSalones.getValueAt(fila, 8).toString());
        txtFPC.setText(tblSalones.getValueAt(fila, 9).toString());
        txtProyec.setText(tblSalones.getValueAt(fila, 10).toString());
        txtFPRO.setText(tblSalones.getValueAt(fila, 11).toString());
        txtBote.setText(tblSalones.getValueAt(fila, 12).toString());
        txtFBB.setText(tblSalones.getValueAt(fila, 13).toString());
        txtMesaban.setText(tblSalones.getValueAt(fila, 14).toString());
        txtFMB.setText(tblSalones.getValueAt(fila, 15).toString());
        txtClima.setText(tblSalones.getValueAt(fila, 16).toString());
        txtLuz.setText(tblSalones.getValueAt(fila, 17).toString());
        txtUbi.setText(tblSalones.getValueAt(fila, 18).toString());
        txtObser.setText(tblSalones.getValueAt(fila, 19).toString());
        
                
    }//GEN-LAST:event_tblSalonesMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        mostrarBuscar(txtBuscarSalon.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIdSalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSalonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSalonKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
       
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtPizarronKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPizarronKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPizarronKeyTyped

    private void txtFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFKeyTyped

    private void txtSillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSillaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtSillaKeyTyped

    private void txtFSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFSKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFSKeyTyped

    private void txtMesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesaKeyTyped
  char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtMesaKeyTyped

    private void txtFMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFMKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFMKeyTyped

    private void txtPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPCKeyTyped

    private void txtFPCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPCKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPCKeyTyped

    /*
    txtId.setText("Ingrese su ID");
        txtNombre.setText("Ingrese su Nombre");
        txtUsuario.setText("Ingrese su Usuario");
        txtnFicha.setText("Ingrese su N.Ficha");
        txtnControl.setText("Ingrese su N.Control");
        txtCarrera.setText("Ingrese su Carrera");
        txtTurno.setText("Ingrese su Turno");
        txtPuesto.setText("Ingrese su Puesto");
        txtInstitucion.setText("Ingrese su Institución");
        txtEscuela.setText("Ingrese su Escuela");
        txtClave.setText("Ingrese su Clave");
        txtConfirmarClave.setText("Confirme su Clave");
        txtBuscar.setText("Ingrese el ID");
    */
    
    private void txtIdSalonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdSalonFocusGained
      if(txtIdSalon.getText().equals("Ingrese su ID")){
         txtIdSalon.setText(null);
         txtIdSalon.requestFocus();
         deleteplaceholder(txtIdSalon);
      //Ingrese el ID   
     }
    }//GEN-LAST:event_txtIdSalonFocusGained

    private void txtIdSalonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdSalonFocusLost
          if(txtIdSalon.getText().length()==0){
          addplaceholder(txtIdSalon);
          txtIdSalon.setText("Ingrese su ID");
      }
    }//GEN-LAST:event_txtIdSalonFocusLost

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
      
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
      
    }//GEN-LAST:event_txtCodigoFocusLost

    private void txtPizarronFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPizarronFocusGained
      
    }//GEN-LAST:event_txtPizarronFocusGained

    private void txtPizarronFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPizarronFocusLost
      
    }//GEN-LAST:event_txtPizarronFocusLost

    private void txtFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFFocusGained
      
    }//GEN-LAST:event_txtFFocusGained

    private void txtFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFFocusLost
       
    }//GEN-LAST:event_txtFFocusLost

    private void txtSillaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusGained
        
    }//GEN-LAST:event_txtSillaFocusGained

    private void txtSillaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSillaFocusLost
       
    }//GEN-LAST:event_txtSillaFocusLost

    private void txtFSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusGained
      
    }//GEN-LAST:event_txtFSFocusGained

    private void txtFSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSFocusLost
      
    }//GEN-LAST:event_txtFSFocusLost

    private void txtMesaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusGained
     
    }//GEN-LAST:event_txtMesaFocusGained

    private void txtMesaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesaFocusLost
        
    }//GEN-LAST:event_txtMesaFocusLost

    private void txtFMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusGained
     
    }//GEN-LAST:event_txtFMFocusGained

    private void txtFMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMFocusLost
     
    }//GEN-LAST:event_txtFMFocusLost

    private void txtPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusGained
     
    }//GEN-LAST:event_txtPCFocusGained

    private void txtPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPCFocusLost
     
    }//GEN-LAST:event_txtPCFocusLost

    private void txtFPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusGained
     
    }//GEN-LAST:event_txtFPCFocusGained

    private void txtFPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPCFocusLost
     
    }//GEN-LAST:event_txtFPCFocusLost

    private void txtBuscarSalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSalonKeyTyped
         
    }//GEN-LAST:event_txtBuscarSalonKeyTyped

    private void txtBuscarSalonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusGained
       if(txtBuscarSalon.getText().equals("Ingrese el Salón")){
         txtBuscarSalon.setText(null);
         txtBuscarSalon.requestFocus();
         deleteplaceholder(txtBuscarSalon);
        
        
     }
    }//GEN-LAST:event_txtBuscarSalonFocusGained

    private void txtBuscarSalonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarSalonFocusLost
        if(txtBuscarSalon.getText().length()==0){
          addplaceholder(txtBuscarSalon);
          txtBuscarSalon.setText("Ingrese el Salón");
      }
    }//GEN-LAST:event_txtBuscarSalonFocusLost

    private void txtPizarronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPizarronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPizarronActionPerformed

    private void txtProyecFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProyecFocusGained
       if(txtProyec.getText().equals("Cantidad de Proyectores")){
         txtProyec.setText(null);
         txtProyec.requestFocus();
         deleteplaceholder(txtProyec);
     }
    }//GEN-LAST:event_txtProyecFocusGained

    private void txtProyecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProyecFocusLost
        if(txtProyec.getText().length()==0){
          addplaceholder(txtProyec);
          txtProyec.setText("Cantidad de Proyectores");
      }
    }//GEN-LAST:event_txtProyecFocusLost

    private void txtProyecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProyecKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtProyecKeyTyped

    private void txtFPROFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPROFocusGained
        if(txtFPRO.getText().equals("Funciona")){
         txtFPRO.setText(null);
         txtFPRO.requestFocus();
         deleteplaceholder(txtFPRO);
     }
    }//GEN-LAST:event_txtFPROFocusGained

    private void txtFPROFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPROFocusLost
       if(txtFPRO.getText().length()==0){
          addplaceholder(txtFPRO);
          txtFPRO.setText("Funciona");
      }
    }//GEN-LAST:event_txtFPROFocusLost

    private void txtFPROKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPROKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFPROKeyTyped

    private void txtBoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusGained
        if(txtBote.getText().equals("Cantidad de Botes")){
         txtBote.setText(null);
         txtBote.requestFocus();
         deleteplaceholder(txtBote);
     }
    }//GEN-LAST:event_txtBoteFocusGained

    private void txtBoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoteFocusLost
        if(txtBote.getText().length()==0){
          addplaceholder(txtBote);
          txtBote.setText("Cantidad de Botes");
      }
    }//GEN-LAST:event_txtBoteFocusLost

    private void txtBoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoteKeyTyped
      char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBoteKeyTyped

    private void txtFBBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusGained
          if(txtFBB.getText().equals("Funciona")){
         txtFBB.setText(null);
         txtFBB.requestFocus();
         deleteplaceholder(txtFBB);
     }
    }//GEN-LAST:event_txtFBBFocusGained

    private void txtFBBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFBBFocusLost
       if(txtFBB.getText().length()==0){
          addplaceholder(txtFBB);
          txtFBB.setText("Funciona");
      }
    }//GEN-LAST:event_txtFBBFocusLost

    private void txtFBBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFBBKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFBBKeyTyped

    private void txtMesabanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesabanFocusGained
        if(txtMesaban.getText().equals("Cantidad de Mesabancos")){
         txtMesaban.setText(null);
         txtMesaban.requestFocus();
         deleteplaceholder(txtMesaban);
     }
    }//GEN-LAST:event_txtMesabanFocusGained

    private void txtMesabanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMesabanFocusLost
        if(txtMesaban.getText().length()==0){
          addplaceholder(txtMesaban);
          txtMesaban.setText("Cantidad de Mesabancos");
      }
    }//GEN-LAST:event_txtMesabanFocusLost

    private void txtMesabanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesabanKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtMesabanKeyTyped

    private void txtFMBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMBFocusGained
         if(txtFMB.getText().equals("Funciona")){
         txtFMB.setText(null);
         txtFMB.requestFocus();
         deleteplaceholder(txtFMB);
     }
    }//GEN-LAST:event_txtFMBFocusGained

    private void txtFMBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFMBFocusLost
       if(txtFMB.getText().length()==0){
          addplaceholder(txtFMB);
          txtFMB.setText("Funciona");
      }
    }//GEN-LAST:event_txtFMBFocusLost

    private void txtFMBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFMBKeyTyped
       char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtFMBKeyTyped

    private void txtClimaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClimaFocusGained
        if(txtClima.getText().equals("Funciona el Clima")){
         txtClima.setText(null);
         txtClima.requestFocus();
         deleteplaceholder(txtClima);
         
     }
    }//GEN-LAST:event_txtClimaFocusGained

    private void txtClimaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClimaFocusLost
        if(txtClima.getText().length()==0){
          addplaceholder(txtClima);
          txtClima.setText("Funciona el Clima");
      }
    }//GEN-LAST:event_txtClimaFocusLost

    private void txtClimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClimaKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtClimaKeyTyped

    private void txtLuzFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLuzFocusGained
                if(txtLuz.getText().equals("Funciona la Luz")){
         txtLuz.setText(null);
         txtLuz.requestFocus();
         deleteplaceholder(txtLuz);
     }
    }//GEN-LAST:event_txtLuzFocusGained

    private void txtLuzFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLuzFocusLost
        if(txtLuz.getText().length()==0){
          addplaceholder(txtLuz);
          txtLuz.setText("Funciona la Luz");
      }
    }//GEN-LAST:event_txtLuzFocusLost

    private void txtLuzKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuzKeyTyped
       char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtLuzKeyTyped

    private void txtUbiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusGained
            if(txtUbi.getText().equals("Ingrese la Ubicación")){
         txtUbi.setText(null);
         txtUbi.requestFocus();
         deleteplaceholder(txtUbi);
     }
    }//GEN-LAST:event_txtUbiFocusGained

    private void txtUbiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbiFocusLost
     if(txtUbi.getText().length()==0){
          addplaceholder(txtUbi);
          txtUbi.setText("Ingrese la Ubicación");
      }
    }//GEN-LAST:event_txtUbiFocusLost

    private void txtUbiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbiKeyTyped
      
    }//GEN-LAST:event_txtUbiKeyTyped

    private void txtObserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusGained
          if(txtObser.getText().equals("Ingrese la Observación")){
         txtObser.setText(null);
         txtObser.requestFocus();
         deleteplaceholder(txtObser);
         
     }
    }//GEN-LAST:event_txtObserFocusGained

    private void txtObserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObserFocusLost
        if(txtObser.getText().length()==0){
          addplaceholder(txtObser);
          txtObser.setText("Ingrese la Observación");
      }
    }//GEN-LAST:event_txtObserFocusLost

    private void txtObserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObserKeyTyped
     
    }//GEN-LAST:event_txtObserKeyTyped

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtBuscarSalonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtBuscarSalonPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarSalonPropertyChange

    private void txtBuscarSalonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBuscarSalonInputMethodTextChanged
       mostrarBuscar(txtBuscarSalon.getText());
    }//GEN-LAST:event_txtBuscarSalonInputMethodTextChanged

    private void txtBuscarSalonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSalonKeyReleased
       mostrarBuscar(txtBuscarSalon.getText());
    }//GEN-LAST:event_txtBuscarSalonKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalones;
    private javax.swing.JTextField txtBote;
    private javax.swing.JTextField txtBuscarSalon;
    private javax.swing.JTextField txtClima;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtFBB;
    private javax.swing.JTextField txtFM;
    private javax.swing.JTextField txtFMB;
    private javax.swing.JTextField txtFPC;
    private javax.swing.JTextField txtFPRO;
    private javax.swing.JTextField txtFS;
    private javax.swing.JTextField txtIdSalon;
    private javax.swing.JTextField txtLuz;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtMesaban;
    private javax.swing.JTextField txtObser;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPizarron;
    private javax.swing.JTextField txtProyec;
    private javax.swing.JTextField txtSilla;
    private javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables

}
