
package IMPORTANTE;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

public class Sistema extends javax.swing.JFrame {

   
    String hora = "";

    public Sistema() {
        initComponents();
        setLocationRelativeTo(null);

        TimerTask tiempotarea = new TimerTask() {
            public void run() {
                Date fecha = new Date();
                DateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
                lblfecha.setText(formatofecha.format(fecha));

                DateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
                lblhora.setText(formatoHora.format(fecha));

                Calendar dt = Calendar.getInstance();
                int hh = dt.get(Calendar.HOUR_OF_DAY);
                int mm = dt.get(Calendar.MINUTE);
                int ss = dt.get(Calendar.SECOND);
                hora = String.valueOf(""+hh+""+mm+""+ss);
            }
        };

        Timer tiempo = new Timer();
        tiempo.scheduleAtFixedRate(tiempotarea, 0, 1000);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnCentral = new javax.swing.JDesktopPane();
        pnSubmenu2 = new javax.swing.JPanel();
        btnSalasSubmenu = new javax.swing.JButton();
        btnSalonesSubmenu = new javax.swing.JButton();
        btnCubiSubmenu2 = new javax.swing.JButton();
        btnJefesSubmenu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuInformacion = new javax.swing.JMenu();
        ItemUsuariosI = new javax.swing.JMenuItem();
        ItemInfo = new javax.swing.JMenuItem();
        ItemInfo1 = new javax.swing.JMenuItem();
        ItemInfo2 = new javax.swing.JMenuItem();
        ISalas = new javax.swing.JMenuItem();
        ISalas1 = new javax.swing.JMenuItem();
        menuUbicacion = new javax.swing.JMenu();
        itemSalonUbi = new javax.swing.JMenuItem();
        itemCubiUbi = new javax.swing.JMenuItem();
        itemDirecUbi = new javax.swing.JMenuItem();
        itemSalasUbi = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnCentral.setBackground(new java.awt.Color(204, 153, 255));

        pnSubmenu2.setBackground(new java.awt.Color(255, 255, 255));
        pnSubmenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSULTAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12))); // NOI18N
        pnSubmenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalasSubmenu.setBackground(new java.awt.Color(153, 255, 153));
        btnSalasSubmenu.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnSalasSubmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seminario.png"))); // NOI18N
        btnSalasSubmenu.setBorderPainted(false);
        btnSalasSubmenu.setContentAreaFilled(false);
        btnSalasSubmenu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seminario.png"))); // NOI18N
        btnSalasSubmenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seminario (1).png"))); // NOI18N
        btnSalasSubmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasSubmenuActionPerformed(evt);
            }
        });
        pnSubmenu2.add(btnSalasSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 50));

        btnSalonesSubmenu.setBackground(new java.awt.Color(153, 255, 153));
        btnSalonesSubmenu.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnSalonesSubmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salon-de-clases.png"))); // NOI18N
        btnSalonesSubmenu.setBorderPainted(false);
        btnSalonesSubmenu.setContentAreaFilled(false);
        btnSalonesSubmenu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salon-de-clases.png"))); // NOI18N
        btnSalonesSubmenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salon-de-clases (1).png"))); // NOI18N
        btnSalonesSubmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalonesSubmenuActionPerformed(evt);
            }
        });
        pnSubmenu2.add(btnSalonesSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, 60));

        btnCubiSubmenu2.setBackground(new java.awt.Color(153, 255, 153));
        btnCubiSubmenu2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnCubiSubmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo (2).png"))); // NOI18N
        btnCubiSubmenu2.setBorderPainted(false);
        btnCubiSubmenu2.setContentAreaFilled(false);
        btnCubiSubmenu2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo (2).png"))); // NOI18N
        btnCubiSubmenu2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo (3).png"))); // NOI18N
        btnCubiSubmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubiSubmenu2ActionPerformed(evt);
            }
        });
        pnSubmenu2.add(btnCubiSubmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, 60));

        btnJefesSubmenu1.setBackground(new java.awt.Color(153, 255, 153));
        btnJefesSubmenu1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnJefesSubmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reunion.png"))); // NOI18N
        btnJefesSubmenu1.setBorderPainted(false);
        btnJefesSubmenu1.setContentAreaFilled(false);
        btnJefesSubmenu1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reunion.png"))); // NOI18N
        btnJefesSubmenu1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reunion (1).png"))); // NOI18N
        btnJefesSubmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJefesSubmenu1ActionPerformed(evt);
            }
        });
        pnSubmenu2.add(btnJefesSubmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 120, 60));

        jLabel1.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Hora:");

        jLabel3.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Fecha:");

        lblusuario.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N

        lblhora.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N

        lblfecha.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N

        menuBar.setBackground(new java.awt.Color(204, 204, 255));
        menuBar.setMaximumSize(new java.awt.Dimension(190, 34769));

        menuInformacion.setBackground(new java.awt.Color(153, 153, 255));
        menuInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/saloness.png"))); // NOI18N
        menuInformacion.setMnemonic('e');
        menuInformacion.setText("Información");
        menuInformacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/saloness.png"))); // NOI18N
        menuInformacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/saloness2.png"))); // NOI18N

        ItemUsuariosI.setBackground(new java.awt.Color(204, 204, 255));
        ItemUsuariosI.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        ItemUsuariosI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        ItemUsuariosI.setMnemonic('y');
        ItemUsuariosI.setText("Usuarios");
        ItemUsuariosI.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        ItemUsuariosI.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user2.png"))); // NOI18N
        ItemUsuariosI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuariosIActionPerformed(evt);
            }
        });
        menuInformacion.add(ItemUsuariosI);

        ItemInfo.setBackground(new java.awt.Color(204, 204, 255));
        ItemInfo.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        ItemInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas.png"))); // NOI18N
        ItemInfo.setMnemonic('y');
        ItemInfo.setText("Salones");
        ItemInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas.png"))); // NOI18N
        ItemInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas2.png"))); // NOI18N
        ItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemInfoActionPerformed(evt);
            }
        });
        menuInformacion.add(ItemInfo);

        ItemInfo1.setBackground(new java.awt.Color(204, 204, 255));
        ItemInfo1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        ItemInfo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo.png"))); // NOI18N
        ItemInfo1.setMnemonic('y');
        ItemInfo1.setText("Cubículos");
        ItemInfo1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo.png"))); // NOI18N
        ItemInfo1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo (1).png"))); // NOI18N
        ItemInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemInfo1ActionPerformed(evt);
            }
        });
        menuInformacion.add(ItemInfo1);

        ItemInfo2.setBackground(new java.awt.Color(204, 204, 255));
        ItemInfo2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        ItemInfo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefes.png"))); // NOI18N
        ItemInfo2.setMnemonic('y');
        ItemInfo2.setText("Directivos");
        ItemInfo2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefes.png"))); // NOI18N
        ItemInfo2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefes_1.png"))); // NOI18N
        ItemInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemInfo2ActionPerformed(evt);
            }
        });
        menuInformacion.add(ItemInfo2);

        ISalas.setBackground(new java.awt.Color(204, 204, 255));
        ISalas.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        ISalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas.png"))); // NOI18N
        ISalas.setMnemonic('y');
        ISalas.setText("Salas");
        ISalas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas.png"))); // NOI18N
        ISalas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas2.png"))); // NOI18N
        ISalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISalasActionPerformed(evt);
            }
        });
        menuInformacion.add(ISalas);

        ISalas1.setBackground(new java.awt.Color(204, 204, 255));
        ISalas1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        ISalas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compras.png"))); // NOI18N
        ISalas1.setMnemonic('y');
        ISalas1.setText("Compras");
        ISalas1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas.png"))); // NOI18N
        ISalas1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas2.png"))); // NOI18N
        ISalas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISalas1ActionPerformed(evt);
            }
        });
        menuInformacion.add(ISalas1);

        menuBar.add(menuInformacion);

        menuUbicacion.setBackground(new java.awt.Color(255, 255, 255));
        menuUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mapa.png"))); // NOI18N
        menuUbicacion.setMnemonic('h');
        menuUbicacion.setText("Ubicación");
        menuUbicacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mapa.png"))); // NOI18N
        menuUbicacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mapa2.png"))); // NOI18N

        itemSalonUbi.setBackground(new java.awt.Color(204, 204, 255));
        itemSalonUbi.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        itemSalonUbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aula.png"))); // NOI18N
        itemSalonUbi.setMnemonic('c');
        itemSalonUbi.setText("Salones");
        itemSalonUbi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aula.png"))); // NOI18N
        itemSalonUbi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aula_1.png"))); // NOI18N
        itemSalonUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalonUbiActionPerformed(evt);
            }
        });
        menuUbicacion.add(itemSalonUbi);

        itemCubiUbi.setBackground(new java.awt.Color(204, 204, 255));
        itemCubiUbi.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        itemCubiUbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo.png"))); // NOI18N
        itemCubiUbi.setMnemonic('c');
        itemCubiUbi.setText("Cubículos");
        itemCubiUbi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo.png"))); // NOI18N
        itemCubiUbi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubiculo (1).png"))); // NOI18N
        itemCubiUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCubiUbiActionPerformed(evt);
            }
        });
        menuUbicacion.add(itemCubiUbi);

        itemDirecUbi.setBackground(new java.awt.Color(204, 204, 255));
        itemDirecUbi.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        itemDirecUbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefes.png"))); // NOI18N
        itemDirecUbi.setMnemonic('c');
        itemDirecUbi.setText("Directivos");
        itemDirecUbi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefes.png"))); // NOI18N
        itemDirecUbi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefes_1.png"))); // NOI18N
        itemDirecUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDirecUbiActionPerformed(evt);
            }
        });
        menuUbicacion.add(itemDirecUbi);

        itemSalasUbi.setBackground(new java.awt.Color(204, 204, 255));
        itemSalasUbi.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        itemSalasUbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas.png"))); // NOI18N
        itemSalasUbi.setMnemonic('c');
        itemSalasUbi.setText("Salas");
        itemSalasUbi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas.png"))); // NOI18N
        itemSalasUbi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salas2.png"))); // NOI18N
        itemSalasUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalasUbiActionPerformed(evt);
            }
        });
        menuUbicacion.add(itemSalasUbi);

        menuBar.add(menuUbicacion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lblhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnSubmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnSubmenu2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addComponent(pnCentral)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void btnSalasSubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasSubmenuActionPerformed
     Salas2 salas2 = new Salas2();
        pnCentral.add(salas2);
        salas2.show();
        
    }//GEN-LAST:event_btnSalasSubmenuActionPerformed

    private void ItemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemInfoActionPerformed
         Salones salones = new Salones();
        pnCentral.add(salones);
        salones.show();
    }//GEN-LAST:event_ItemInfoActionPerformed

    private void ItemInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemInfo1ActionPerformed
       Cubiculos cubi = new Cubiculos();
        pnCentral.add(cubi);
        cubi.show();
    }//GEN-LAST:event_ItemInfo1ActionPerformed

    private void ItemInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemInfo2ActionPerformed
          Jefes miJe = new Jefes();
        pnCentral.add(miJe);
        miJe.show();
    }//GEN-LAST:event_ItemInfo2ActionPerformed

    private void ISalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISalasActionPerformed
         Salas miSalas = new Salas();
        pnCentral.add(miSalas);
        miSalas.show();
    }//GEN-LAST:event_ISalasActionPerformed

    private void itemSalonUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalonUbiActionPerformed
          SalonesUbi miUs = new SalonesUbi();
        pnCentral.add(miUs);
        miUs.show();
    }//GEN-LAST:event_itemSalonUbiActionPerformed

    private void itemCubiUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCubiUbiActionPerformed
          CubiculosUbi miUs = new CubiculosUbi();
        pnCentral.add(miUs);
        miUs.show();
    }//GEN-LAST:event_itemCubiUbiActionPerformed

    private void itemDirecUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDirecUbiActionPerformed
        JefesUbi miUs = new JefesUbi();
        pnCentral.add(miUs);
        miUs.show();
    }//GEN-LAST:event_itemDirecUbiActionPerformed

    private void itemSalasUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalasUbiActionPerformed
       SalasUbi miUs = new SalasUbi();
        pnCentral.add(miUs);
        miUs.show();
    }//GEN-LAST:event_itemSalasUbiActionPerformed

    private void ItemUsuariosIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuariosIActionPerformed
       Usuarios miUs = new Usuarios();
        pnCentral.add(miUs);
        miUs.show();
    }//GEN-LAST:event_ItemUsuariosIActionPerformed

    private void btnSalonesSubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalonesSubmenuActionPerformed
       Salones2 sa2 = new Salones2();
        pnCentral.add(sa2);
        sa2.show();
    }//GEN-LAST:event_btnSalonesSubmenuActionPerformed

    private void btnCubiSubmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubiSubmenu2ActionPerformed
        Cubiculos2 cu2 = new Cubiculos2();
        pnCentral.add(cu2);
        cu2.show();
    }//GEN-LAST:event_btnCubiSubmenu2ActionPerformed

    private void btnJefesSubmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJefesSubmenu1ActionPerformed
        Jefes2 je2 = new Jefes2();
        pnCentral.add(je2);
        je2.show();    }//GEN-LAST:event_btnJefesSubmenu1ActionPerformed

    private void ISalas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISalas1ActionPerformed
         Compras compra = new Compras();
        pnCentral.add(compra);
        compra.show();
    }//GEN-LAST:event_ISalas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ISalas;
    private javax.swing.JMenuItem ISalas1;
    private javax.swing.JMenuItem ItemInfo;
    private javax.swing.JMenuItem ItemInfo1;
    private javax.swing.JMenuItem ItemInfo2;
    private javax.swing.JMenuItem ItemUsuariosI;
    private javax.swing.JButton btnCubiSubmenu2;
    private javax.swing.JButton btnJefesSubmenu1;
    private javax.swing.JButton btnSalasSubmenu;
    private javax.swing.JButton btnSalonesSubmenu;
    private javax.swing.JMenuItem itemCubiUbi;
    private javax.swing.JMenuItem itemDirecUbi;
    private javax.swing.JMenuItem itemSalasUbi;
    private javax.swing.JMenuItem itemSalonUbi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuInformacion;
    private javax.swing.JMenu menuUbicacion;
    private javax.swing.JDesktopPane pnCentral;
    private javax.swing.JPanel pnSubmenu2;
    // End of variables declaration//GEN-END:variables

    public void setDatos(String usuario, String perfil) {
        lblusuario.setText(usuario);
      
        if (perfil.equals("Jefe")) {
            
        } else if(perfil.equals("Profesor")) {
            //menuConsultas.setVisible(false);
           
            //ItemUsuarios.setVisible(false);
            menuInformacion.setVisible(false);
            
            
        }else if(perfil.equals("Servicio Social")){
            
        }else if(perfil.equals("Invitado")){
            //menuConsultas.setVisible(false);
          
            // ItemUsuarios.setVisible(false);
            menuInformacion.setVisible(false);
            
            
        }
    }

}
