
package IMPORTANTE;

import DTOS.UsuariosDto;
import DAOS.UsuariosDao;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class Usuarios extends javax.swing.JInternalFrame {

   
    
      UsuariosDto usDto = new UsuariosDto();
            UsuariosDao usDao = new UsuariosDao();
    
    public Usuarios() {
        initComponents();
        txtIdUsuarios.setVisible(false);
        txtIdUsuarios.setEnabled(false);
        lblusuario.setVisible(true);
        lblidUsu.setVisible(true);
        limpiar();
        habilitar(true);
        mostrarBuscar("");
        lblusuario.setText(usDto.getUsuario());
        

      
       
    }
    
     
      /* public void setDatos(String usuario, String idsu) {
        lblusuario.setText(usuario);
        lblidUsu.setText(idsu);
       }*/
            
    
    public void addplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
       
    }
    public void deleteplaceholder(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public void mostrarBuscar(String usuario) {
        DefaultTableModel miModelo;
        UsuariosDao fn = new UsuariosDao();
        UsuariosDto dts = new UsuariosDto();
        dts.setUsuario(usuario);
        miModelo = fn.mostrarUsuarios(dts);
        tblUsuarios.setModel(miModelo);

    }
    

    public void limpiar() {
        txtIdUsuarios.setText("");
        txtNombre.setText("");
        txtUsuario.setText("");
        txtnFicha.setText("");
        txtnControl.setText("");
        txtCarrera.setText("");
        txtTurno.setText("");
        txtPuesto.setText("");
        txtInstitucion.setText("");
        txtEscuela.setText("");
        txtClave.setText("");
        txtPerfil.setText("");
       // txtConfirmarClave.setText("");
       
      //  cmbPerfil.setSelectedIndex(1);
        txtBuscar.setText("");
    }

    public void habilitar(boolean b) {
        txtNombre.setEnabled(!b);
        txtUsuario.setEnabled(!b);
        txtnFicha.setEnabled(!b);
        txtnControl.setEnabled(!b);
        txtCarrera.setEnabled(!b);
        txtTurno.setEnabled(!b);
        txtPuesto.setEnabled(!b);
        txtInstitucion.setEnabled(!b);
        txtEscuela.setEnabled(!b);
        txtClave.setEnabled(!b);
        txtPerfil.setEnabled(!b);
        BoxShowpass.setEnabled(!b);
       // txtConfirmarClave.setEnabled(!b);
        //cmbPerfil.setEnabled(!b);

        btnNuevo.setEnabled(b);
        btnEditar.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtIdUsuarios = new javax.swing.JTextField();
        txtnFicha = new javax.swing.JTextField();
        txtnControl = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        txtTurno = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        txtInstitucion = new javax.swing.JTextField();
        txtPerfil = new javax.swing.JTextField();
        BoxShowpass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblidUsu = new javax.swing.JLabel();
        txtEscuela = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(909, 480));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setText("Perfil:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 100, -1));

        txtIdUsuarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdUsuariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdUsuariosFocusLost(evt);
            }
        });
        txtIdUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdUsuariosKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 10, 10));

        txtnFicha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnFichaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnFichaFocusLost(evt);
            }
        });
        txtnFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnFichaKeyTyped(evt);
            }
        });
        jPanel1.add(txtnFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, -1));

        txtnControl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnControlFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnControlFocusLost(evt);
            }
        });
        txtnControl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnControlKeyTyped(evt);
            }
        });
        jPanel1.add(txtnControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, -1));

        txtCarrera.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCarreraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCarreraFocusLost(evt);
            }
        });
        txtCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarreraKeyTyped(evt);
            }
        });
        jPanel1.add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 90, -1));

        txtTurno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTurnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTurnoFocusLost(evt);
            }
        });
        txtTurno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTurnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, -1));

        txtPuesto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPuestoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPuestoFocusLost(evt);
            }
        });
        txtPuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuestoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 90, -1));

        txtInstitucion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInstitucionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInstitucionFocusLost(evt);
            }
        });
        txtInstitucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInstitucionKeyTyped(evt);
            }
        });
        jPanel1.add(txtInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 90, -1));

        txtPerfil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPerfilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPerfilFocusLost(evt);
            }
        });
        txtPerfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPerfilKeyTyped(evt);
            }
        });
        jPanel1.add(txtPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 90, -1));

        BoxShowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxShowpassActionPerformed(evt);
            }
        });
        jPanel1.add(BoxShowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel1.setText("Contraseña:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo (1).png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 50, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, 30));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setText("N.Control:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel9.setText("N.Ficha:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel10.setText("Usuario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel11.setText("Carrera:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel12.setText("Turno:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel13.setText("Puesto:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel14.setText("Institu:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel15.setText("Escuela:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel16.setText("Clave:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        lblusuario.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jPanel1.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 90, 20));

        lblidUsu.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jPanel1.add(lblidUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 70, 20));

        txtEscuela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEscuelaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEscuelaFocusLost(evt);
            }
        });
        txtEscuela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEscuelaKeyTyped(evt);
            }
        });
        jPanel1.add(txtEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 90, -1));

        txtClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClaveFocusLost(evt);
            }
        });
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 90, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblUsuarios.setBackground(new java.awt.Color(153, 153, 255));
        tblUsuarios.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "USUARIO", "NFicha", "NControl", "Carrera", "Turno", "Puesto", "Institucion", "Escuela", "PERFIL"
            }
        ));
        tblUsuarios.setSelectionBackground(new java.awt.Color(255, 102, 255));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (2).png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar (3).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        habilitar(false);
        
                
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        int fu = tblUsuarios.rowAtPoint(evt.getPoint());
        txtIdUsuarios.setText(tblUsuarios.getValueAt(fu, 0).toString());

        int nom = tblUsuarios.rowAtPoint(evt.getPoint());
        txtNombre.setText(tblUsuarios.getValueAt(nom, 1).toString());
        
        int usu = tblUsuarios.rowAtPoint(evt.getPoint());
        txtUsuario.setText(tblUsuarios.getValueAt(usu, 2).toString());
        
        int nf = tblUsuarios.rowAtPoint(evt.getPoint());
        txtnFicha.setText(tblUsuarios.getValueAt(nf, 3).toString());
        
        int nc = tblUsuarios.rowAtPoint(evt.getPoint());
        txtnControl.setText(tblUsuarios.getValueAt(nc, 4).toString());
        
        int car = tblUsuarios.rowAtPoint(evt.getPoint());
        txtCarrera.setText(tblUsuarios.getValueAt(car, 5).toString());
        
        int tur = tblUsuarios.rowAtPoint(evt.getPoint());
        txtTurno.setText(tblUsuarios.getValueAt(tur, 6).toString());
        
        int pue = tblUsuarios.rowAtPoint(evt.getPoint());
        txtPuesto.setText(tblUsuarios.getValueAt(pue, 7).toString());
        
        int ins = tblUsuarios.rowAtPoint(evt.getPoint());
        txtInstitucion.setText(tblUsuarios.getValueAt(ins, 8).toString());
        
        int esc = tblUsuarios.rowAtPoint(evt.getPoint());
        txtEscuela.setText(tblUsuarios.getValueAt(esc, 9).toString());
        
         int cla = tblUsuarios.rowAtPoint(evt.getPoint());
        txtClave.setText(tblUsuarios.getValueAt(cla, 10).toString());
       
        int per = tblUsuarios.rowAtPoint(evt.getPoint());
        txtPerfil.setText(tblUsuarios.getValueAt(per, 11).toString());
        
      
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        mostrarBuscar(txtBuscar.getText());
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BoxShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxShowpassActionPerformed
        if(BoxShowpass.isSelected()){
            txtClave.setEchoChar((char)0);
            //txtConfirmarClave.setEchoChar((char)0);
        } else{
            txtClave.setEchoChar('*');
            //txtConfirmarClave.setEchoChar('*');
        }

    }//GEN-LAST:event_BoxShowpassActionPerformed

    private void txtIdUsuariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdUsuariosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuariosKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtnFichaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnFichaKeyTyped
         char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtnFichaKeyTyped

    private void txtnControlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnControlKeyTyped
           char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtnControlKeyTyped

    private void txtCarreraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarreraKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtCarreraKeyTyped

    private void txtTurnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTurnoKeyTyped
     char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtTurnoKeyTyped

    private void txtPuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuestoKeyTyped
         char c = evt.getKeyChar();
    if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtPuestoKeyTyped

    private void txtInstitucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstitucionKeyTyped
        
    }//GEN-LAST:event_txtInstitucionKeyTyped

    private void txtPerfilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPerfilKeyTyped
         
    }//GEN-LAST:event_txtPerfilKeyTyped

   
    
    private void txtIdUsuariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdUsuariosFocusGained
      if(txtIdUsuarios.getText().equals("")){
         txtIdUsuarios.setText(null);
         txtIdUsuarios.requestFocus();
         deleteplaceholder(txtIdUsuarios);
      //Ingrese el ID   
     }
    }//GEN-LAST:event_txtIdUsuariosFocusGained

    private void txtIdUsuariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdUsuariosFocusLost
          if(txtIdUsuarios.getText().length()==0){
          addplaceholder(txtIdUsuarios);
          //txtIdUsuarios.setText("Ingrese su ID");
      }
    }//GEN-LAST:event_txtIdUsuariosFocusLost

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
      
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(txtNombre.getText().length()==0){
          addplaceholder(txtNombre);
       //   txtNombre.setText("Ingrese su Nombre");
      }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
       if(txtUsuario.getText().equals("")){
         txtUsuario.setText(null);
         txtUsuario.requestFocus();
         deleteplaceholder(txtUsuario);
      
     }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if(txtUsuario.getText().length()==0){
          addplaceholder(txtUsuario);
          //txtUsuario.setText("Ingrese su Usuario");
      }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtnFichaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnFichaFocusGained
      if(txtnFicha.getText().equals("")){
         txtnFicha.setText(null);
         txtnFicha.requestFocus();
         deleteplaceholder(txtnFicha);
       }
    }//GEN-LAST:event_txtnFichaFocusGained

    private void txtnFichaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnFichaFocusLost
        
    }//GEN-LAST:event_txtnFichaFocusLost

    private void txtnControlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnControlFocusGained
        
    }//GEN-LAST:event_txtnControlFocusGained

    private void txtnControlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnControlFocusLost
       
    }//GEN-LAST:event_txtnControlFocusLost

    private void txtCarreraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCarreraFocusGained
     
    }//GEN-LAST:event_txtCarreraFocusGained

    private void txtCarreraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCarreraFocusLost
         
    }//GEN-LAST:event_txtCarreraFocusLost

    private void txtTurnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTurnoFocusGained
   
    }//GEN-LAST:event_txtTurnoFocusGained

    private void txtTurnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTurnoFocusLost
       
    }//GEN-LAST:event_txtTurnoFocusLost

    private void txtPuestoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPuestoFocusGained
     
    }//GEN-LAST:event_txtPuestoFocusGained

    private void txtPuestoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPuestoFocusLost
     
    }//GEN-LAST:event_txtPuestoFocusLost

    private void txtInstitucionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstitucionFocusGained
       
    }//GEN-LAST:event_txtInstitucionFocusGained

    private void txtInstitucionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstitucionFocusLost
       
    }//GEN-LAST:event_txtInstitucionFocusLost

    private void txtPerfilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPerfilFocusGained
     
    }//GEN-LAST:event_txtPerfilFocusGained

    private void txtPerfilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPerfilFocusLost
     
    }//GEN-LAST:event_txtPerfilFocusLost

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
          
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
       
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
       
    }//GEN-LAST:event_txtBuscarFocusLost

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void tblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseExited
       
    }//GEN-LAST:event_tblUsuariosMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        String msg = null;
        if (txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nombre obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocusInWindow();
            return;
        }
        if (txtUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Usuario obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtUsuario.requestFocusInWindow();
            return;
        }
      
        String clave = new String(txtClave.getPassword());
        String confclave = new String(txtClave.getPassword());
        if (clave.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo clave obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtClave.requestFocusInWindow();
            return;
        }
        
     
        if (txtPerfil.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo perfil obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtPerfil.requestFocusInWindow();
            return;
        }
        if (txtIdUsuarios.getText().equals("")) {
            UsuariosDto usuDto = new UsuariosDto();
            UsuariosDao usuDao = new UsuariosDao(); 
            
            //String perfil = String.valueOf(cmbPerfil.getSelectedItem());
            usuDto.setNombre(txtNombre.getText() );
            usuDto.setUsuario(txtUsuario.getText());
            usuDto.setNumFicha(txtnFicha.getText());
            usuDto.setNumControl(txtnControl.getText());
            usuDto.setCarrera(txtCarrera.getText());
            usuDto.setTurno(txtTurno.getText());
            usuDto.setPuesto(txtPuesto.getText());
            usuDto.setInstitucion(txtInstitucion.getText());
            usuDto.setEscuela(txtEscuela.getText());
            usuDto.setClave(txtClave.getText());
            usuDto.setPerfil(txtPerfil.getText());
            
            
            msg = usuDao.insertarUsuarios(usuDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Usuario Agregado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            UsuariosDto usDto = new UsuariosDto();
            UsuariosDao usDao = new UsuariosDao();
           
        //    String perfil = String.valueOf(cmbPerfil.getSelectedItem());

            usDto.setIdUsuarios(Integer.parseInt(txtIdUsuarios.getText()));
            usDto.setNombre(txtNombre.getText());
            usDto.setUsuario(txtUsuario.getText());
            usDto.setNumFicha(txtnFicha.getText());
            usDto.setNumControl(txtnControl.getText());
            usDto.setCarrera(txtCarrera.getText());
            usDto.setTurno(txtTurno.getText());
            usDto.setPuesto(txtPuesto.getText());
            usDto.setInstitucion(txtInstitucion.getText());
            usDto.setEscuela(txtEscuela.getText());
            usDto.setClave(txtClave.getText());
            usDto.setPerfil(txtPerfil.getText());
            
          
            msg = usDao.editarUsuarios(usDto);
            JOptionPane.showMessageDialog(rootPane, msg, "Usuario Modificado", JOptionPane.INFORMATION_MESSAGE);
        }
       
       
        
        habilitar(true);
        mostrarBuscar("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
        mostrarBuscar("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         String msg = null;
        if (txtIdUsuarios.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un registro de la tabla para eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
        } else {
            UsuariosDto dts = new UsuariosDto();
            UsuariosDao fun = new UsuariosDao();

            dts.setIdUsuarios(Integer.parseInt(txtIdUsuarios.getText()));

            msg = fun.eliminarUsuarios(dts);
            JOptionPane.showMessageDialog(rootPane, msg, "Usuario Eliminado", JOptionPane.INFORMATION_MESSAGE);
        }
        mostrarBuscar("");
       
       limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtEscuelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEscuelaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscuelaFocusGained

    private void txtEscuelaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEscuelaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscuelaFocusLost

    private void txtEscuelaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEscuelaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscuelaKeyTyped

    private void txtClaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveFocusGained

    private void txtClaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BoxShowpass;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblidUsu;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtEscuela;
    private javax.swing.JTextField txtIdUsuarios;
    private javax.swing.JTextField txtInstitucion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtTurno;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtnControl;
    private javax.swing.JTextField txtnFicha;
    // End of variables declaration//GEN-END:variables

}
